### ISSUE TITLE
kubeadm reset fails in case of external etcd

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1273]
kubeadm (v1.13.0-beta.2) reset fail in case of external etcd

```
    [preflight] running pre-flight checks
    [reset] Reading configuration from the cluster...
    [reset] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x13a0c48]

goroutine 1 [running]:
k8s.io/kubernetes/cmd/kubeadm/app/cmd.getEtcdDataDir(0xc000461350, 0x23, 0x1916f00, 0xc0000cd680, 0x0, 0x0, 0x0, 0x76)
	cmd/kubeadm/app/cmd/reset.go:211 +0x2f8
k8s.io/kubernetes/cmd/kubeadm/app/cmd.(*Reset).Run(0xc000470920, 0x18cb5e0, 0xc000094008, 0x1916f00, 0xc0000cd680, 0x13, 0x171274e)
	cmd/kubeadm/app/cmd/reset.go:135 +0x12b
k8s.io/kubernetes/cmd/kubeadm/app/cmd.NewCmdReset.func1(0xc000137400, 0xc000523840, 0x0, 0x1)
	cmd/kubeadm/app/cmd/reset.go:71 +0x211
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc000137400, 0xc000523810, 0x1, 0x1, 0xc000137400, 0xc000523810)
	vendor/github.com/spf13/cobra/command.go:760 +0x2cc
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00037b400, 0xc00037b180, 0xc0003c6000, 0xc0003d3260)
	vendor/github.com/spf13/cobra/command.go:846 +0x2fd
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc00037b400, 0xc000094000, 0x18cb5e0)
	vendor/github.com/spf13/cobra/command.go:794 +0x2b
k8s.io/kubernetes/cmd/kubeadm/app.Run(0xc000096120, 0x18b)
	cmd/kubeadm/app/kubeadm.go:48 +0x202
main.main()
	cmd/kubeadm/kubeadm.go:29 +0x33
```

**Comment by neolit123** [comment]
the problem is here:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/reset.go#L64-L67
cc @yagonobre 

i can send a patch for this after 8 PM UTC.

**Comment by yagonobre** [comment]
@neolit123 I guess that the problem is on https://github.com/kubernetes/kubernetes/blob/94759c165f2320b6bca8ff43a40728c357d3afd7/cmd/kubeadm/app/cmd/reset.go#L210

We need `if err == nil  && cfg.Etcd.Local != nil`, I'm creating a etcd cluster to validate the fix

**Comment by yagonobre** [comment]
I teste with `if err == nil && cfg.Etcd.Local != nil` and this work!
