### ISSUE TITLE
badly formated --discovery flag value causes a panic

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubeadm#157]
Something like
```
kubeadm join --skip-preflight-checks --discovery=token://81b2b0:c6c1cbd142c77d4c@ 172.31.0.157 :9898
```

or 
```
kubeadm join --skip-preflight-checks --discovery=token://81b2b0:c6c1cbd142c77d4c 
```

results in this:
```
[kubeadm] WARNING: kubeadm is in alpha, please do not use it for production clusters.
[preflight] Skipping pre-flight checks
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x18e5d20, 0xc42000e070)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
k8s.io/kubernetes/cmd/kubeadm/app/node.RetrieveTrustedClusterInfo(0xc4203a3480, 0x1, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/node/discovery.go:36 +0xa6d
k8s.io/kubernetes/cmd/kubeadm/app/discovery.runTokenDiscovery(0xc4203a3480, 0xc4202e1530, 0xc4202e1530, 0xc4205f5b98)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/discovery/discovery.go:72 +0x54
k8s.io/kubernetes/cmd/kubeadm/app/discovery.For(0x0, 0x0, 0xc4203a3480, 0x5ce4e9, 0x18eeb00, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/discovery/discovery.go:39 +0x50
k8s.io/kubernetes/cmd/kubeadm/app/cmd.(*Join).Run(0xc42008a198, 0x25a8d00, 0xc420022010, 0x2, 0x4)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/join.go:134 +0x59
k8s.io/kubernetes/cmd/kubeadm/app/cmd.NewCmdJoin.func1(0xc42014fb00, 0xc4203a3400, 0x2, 0x4)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/join.go:70 +0xf3
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc42014fb00, 0xc4203a33c0, 0x4, 0x4, 0xc42014fb00, 0xc4203a33c0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:603 +0x439
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42014f440, 0xc42014fd40, 0xc42014fb00, 0xc42014f680)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:689 +0x367
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42014f440, 0xc42033aed0, 0x25a8cc0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:648 +0x2b
k8s.io/kubernetes/cmd/kubeadm/app.Run(0xc4205f5f50, 0xc4200001a0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:35 +0xe8
main.main()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:26 +0x22
```

**Comment by errordeveloper** [comment]
Also there is a reference to `--token` [here](https://github.com/kubernetes/kubernetes/blob/6f37347fce8d3a9fb36a6acbccb57722ae0b9976/cmd/kubeadm/app/cmd/cmd.go#L58).
