### ISSUE TITLE
kubeadm ex token delete causes a panic

### ISSUE THREAD

**Issue by xilabao** [kubernetes/kubeadm#162]
```
#kubeadm ex token delete
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x1964940, 0xc420010100)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
k8s.io/kubernetes/cmd/kubeadm/app/cmd.NewCmdToken.func4(0xc42043f440, 0x26faef8, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/token.go:95 +0x84
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc42043f440, 0x26faef8, 0x0, 0x0, 0xc42043f440, 0x26faef8)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:603 +0x439
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42045dd40, 0xc42044ed80, 0xc42044eb40, 0xc42044e000)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:689 +0x367
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42045dd40, 0xc4202ecb40, 0x2669080)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:648 +0x2b
k8s.io/kubernetes/cmd/kubeadm/app.Run(0xc420607f50, 0xc4200001a0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:35 +0xe8
main.main()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:26 +0x22
```

**Comment by luxas** [comment]
fixed in https://github.com/kubernetes/kubernetes/pull/41342
