### ISSUE TITLE
Kinder gets error when do kubeabm-init

### ISSUE THREAD

**Issue by namnx228** [kubernetes/kubeadm#1705]
## Versions

**kubeadm version** (use `kubeadm version`):
```sh
kinder version: 0.1.0-alpha.3
kind   version: v0.4.0
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
```sh
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- **Cloud provider or hardware configuration**:
I test on two platforms: VM spawned from Openstack  and my laptop
- **OS** (e.g. from /etc/os-release):
```sh
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- **Kernel** (e.g. `uname -a`):
```sh
Linux server-0730-1211 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- **Others**:

## What happened?
After installing kinder, I ran:
```sh
$ kinder create cluster
$ kinder do kubeadm-init
```
and get this error:
```sh
test_cluster-control-plane:$ Checking pre-loaded images
[docker.io/kindest/kindnetd:0.5.0 k8s.gcr.io/coredns:1.3.1 k8s.gcr.io/etcd:3.3.10 k8s.gcr.io/kube-apiserver:v1.15.0 k8s.gcr.io/kube-controller-manager:v1.15.0 k8s.gcr.io/kube-proxy:v1.15.0 k8s.gcr.io/kube-scheduler:v1.15.0 k8s.gcr.io/pause:3.1 sha256:241709fdde11b50175f296c6c88c103ceb845dea69f27b350bebfc04c60a3155 sha256:28bdc6f28a8d9b7ea12e35e46e7cb071946c0ba6bddf59d905aee4a1cd9c8b1b sha256:2c4adeb21b4ff8ed3309d0e42b6b4ae39872399f7b37e0856e673b13c4aba13d sha256:4ccdc592ea9c4c743994bef5b0563cb47bd5133c240bc9b49dd56f16afdcc829 sha256:da86e6ba6ca197bf6bc5e9d900febd906b133eaa4750e6bed647b0fbe50ed43e sha256:e855173d0e51ed7a6094e1564c8284cade41299596d18e991cbf814241f52bae sha256:eb516548c180f8a6e0235034ccee2428027896af16a509786da13022fe95fe8c sha256:ef97cccdfdb5048fe112cf868b2779e06dea11b0d742aad14d4bea690f653549]
<nil>
All the requested images are already pre-loaded into the container runtime

test_cluster-control-plane:$ Preparing /kind/kubeadm.conf
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x10546d9]

goroutine 1 [running]:
sigs.k8s.io/kind/pkg/cluster/nodes.(*Node).test_usere(...)
	/home/test_user/go/pkg/mod/sigs.k8s.io/kind@v0.4.0/pkg/cluster/nodes/node.go:119
k8s.io/kubeadm/kinder/pkg/cluster/status.(*Node).test_usere(...)
	/home/test_user/go/src/kubeadm/kinder/pkg/cluster/status/node.go:72
k8s.io/kubeadm/kinder/pkg/cluster/status.(*Node).Infof(0x0, 0x13293b5, 0x43, 0xc00014fa58, 0x1, 0x1)
	/home/test_user/go/src/kubeadm/kinder/pkg/cluster/status/node.go:169 +0x39
k8s.io/kubeadm/kinder/pkg/cluster/manager/actions.LoadBalancer(0xc0002da780, 0xc00014fae8, 0x1, 0x1, 0x1, 0x0)
	/home/test_user/go/src/kubeadm/kinder/pkg/cluster/manager/actions/loadbalancer.go:38 +0xc4
k8s.io/kubeadm/kinder/pkg/cluster/manager/actions.KubeadmInit(0xc0002da780, 0x0, 0x45d964b800, 0x0, 0xc000458101, 0xc0004c8f70)
	/home/test_user/go/src/kubeadm/kinder/pkg/cluster/manager/actions/kubeadm-init.go:61 +0x133
k8s.io/kubeadm/kinder/pkg/cluster/manager/actions.glob..func3(0xc0002da780, 0xc00036c4a0, 0x7ffc49a6761b, 0xc)
	/home/test_user/go/src/kubeadm/kinder/pkg/cluster/manager/actions/actions.go:45 +0x59
k8s.io/kubeadm/kinder/pkg/cluster/manager/actions.Run(0xc0002da780, 0x7ffc49a6761b, 0xc, 0xc000153ce0, 0x6, 0x6, 0x1, 0x107f7dd)
	/home/test_user/go/src/kubeadm/kinder/pkg/cluster/manager/actions/actions.go:142 +0xe2
k8s.io/kubeadm/kinder/pkg/cluster/manager.(*ClusterManager).DoAction(0xc00036c480, 0x7ffc49a6761b, 0xc, 0xc000153ce0, 0x6, 0x6, 0x1, 0x8010101)
	/home/test_user/go/src/kubeadm/kinder/pkg/cluster/manager/manage.go:91 +0xec
k8s.io/kubeadm/kinder/cmd/kinder/do.runE(0xc000526060, 0xc000154f00, 0xc0004b8180, 0x1, 0x3, 0x0, 0x0)
	/home/test_user/go/src/kubeadm/kinder/cmd/kinder/do/do.go:135 +0x22e
k8s.io/kubeadm/kinder/cmd/kinder/do.NewCommand.func1(0xc000154f00, 0xc0004b8180, 0x1, 0x3, 0x0, 0x0)
	/home/test_user/go/src/kubeadm/kinder/cmd/kinder/do/do.go:56 +0x52
github.com/spf13/cobra.(*Command).execute(0xc000154f00, 0xc0004b8120, 0x3, 0x3, 0xc000154f00, 0xc0004b8120)
	/home/test_user/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001d4000, 0xc0000ca150, 0x137d2e8, 0xc0000ca150)
	/home/test_user/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/test_user/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
k8s.io/kubeadm/kinder/cmd/kinder.Run(0xc0000ca120, 0x14ad180)
	/home/test_user/go/src/kubeadm/kinder/cmd/kinder/kinder.go:110 +0x28
k8s.io/kubeadm/kinder/cmd/kinder.Main()
	/home/test_user/go/src/kubeadm/kinder/cmd/kinder/kinder.go:127 +0xd3
main.main()
	/home/test_user/go/src/kubeadm/kinder/main.go:25 +0x20
```

## What you expected to happen?
The Kubernetes cluster should be created.

## How to reproduce it (as minimally and precisely as possible)?
In `What happens` section

**Comment by namnx228** [comment]
One more thing I should mention, the error occurs when I checkout the latest commit  (d357b4dccc4f198f47f3acd3304d9126104f94a3), and when I checkout the older one (e90d3a7a43d7196b3e2c22e26cfa8a6e80c0e012), it works fine.

**Comment by neolit123** [comment]
hi what is the command line you are calling?

**Comment by namnx228** [comment]
> hi what is the command line you are calling?

I'm using bash

**Comment by neolit123** [comment]
no, i meant what `kinder` commands are you calling that result in the error?

**Comment by namnx228** [comment]
I have put them into the issue message and I will rewrite here:
```sh
$ kinder create cluster
$ kinder do kubeadm-init
```

**Comment by neolit123** [comment]
/assign @fabriziopandini 
i can try taking a look later too.

**Comment by neolit123** [comment]
@namnx228 
i cannot reproduce the problem with the latest commit from master:
e84dff09d44e523182fd34315b0309a49adeb64f

```
$ git pull origin master
$ git rev-parse HEAD
e84dff09d44e523182fd34315b0309a49adeb64f
$ cd kinder
$ GO111MODULE=on go build
$ ./kinder version
kinder version: 0.1.0-alpha.3
kind   version: v0.4.0
$ ./kinder create cluster
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.15.0) 🖼 
 ✓ Preparing nodes 📦 

Nodes creation complete. You can now continue creating a Kubernetes cluster using
kinder do, the kinder swiss knife 🚀!
$ ./kinder do kubeadm-init
...
Cluster creation complete. You can now use the cluster with:

export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"
kubectl cluster-info
```

please re-open if it's still failing for you with this commit.

**Comment by namnx228** [comment]
Can you try to reproduce on a fresh new machine (or VM) ? I faced this error when running kinder for first time.

**Comment by neolit123** [comment]
the bug should be fixed in https://github.com/kubernetes/kubeadm/commit/e84dff09d44e523182fd34315b0309a49adeb64f and later. but it was a real bug.

before:

https://github.com/kubernetes/kubeadm/blob/d357b4dccc4f198f47f3acd3304d9126104f94a3/kinder/pkg/cluster/manager/actions/loadbalancer.go#L37-L43

after:

https://github.com/kubernetes/kubeadm/blob/master/kinder/pkg/cluster/manager/actions/loadbalancer.go#L37-L47

**Comment by namnx228** [comment]
Cool. Nice to see that it was fixed.
