### ISSUE TITLE
panic: assignment to entry in nil map in KubeProxy FeatureGate Configuration

### ISSUE THREAD

**Issue by Arvinderpal** [kubernetes/kubeadm#1929]
BUG REPORT 

**kubeadm version** (use `kubeadm version`):
v1.18.0-alpha.0.1110+3c5dad61f72cc0

## What happened?

```   
    k8s1: panic: assignment to entry in nil map
    k8s1: goroutine 1 [running]:
    k8s1: k8s.io/kubernetes/cmd/kubeadm/app/componentconfigs.DefaultKubeProxyConfiguration(0xc0003c5420)
    k8s1:       /home/awander/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubeadm/app/componentconfigs/defaults.go:84 +0x146
    k8s1: k8s.io/kubernetes/cmd/kubeadm/app/componentconfigs.(*Registrations).Default(0x2978348, 0xc0003c5420)
    k8s1:       /home/awander/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubeadm/app/componentconfigs/registrations.go:147 +0xdf
    k8s1: k8s.io/kubernetes/cmd/kubeadm/app/util/config.SetClusterDynamicDefaults(0xc0003c5420, 0xc0002c2600, 0xc, 0x192b, 0x29700f0, 0xc000613948)
    k8s1:       /home/awander/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubeadm/app/util/config/initconfiguration.go:146 +0x3e
    k8s1: k8s.io/kubernetes/```
```

## How to reproduce it (as minimally and precisely as possible)?

Specify KubeProxyConfiguration below as part of the init configuration. Note that feature-gate field is not present and is only set in the ClusterConfiguration
```---
kind: KubeProxyConfiguration
apiVersion: kubeproxy.config.k8s.io/v1alpha1
mode: ${KUBEPROXY_MODE}```
```
```
kind: ClusterConfiguration
...
featureGates:
  IPv6DualStack: true 
```
## Anything else we need to know?

The following commit may have introduced this bug: https://github.com/kubernetes/kubernetes/commit/994df0d6318759a6de6e3ae18a4ef6cd98fb102b

@neolit123 @rosti

**Comment by rosti** [comment]
Thanks for filing this @Arvinderpal !
/kind bug
