### ISSUE TITLE
kubeadm: creating new v1.17.4 cluster cannot start kube-apiserver pod after reboot of node

### ISSUE THREAD

**Issue by dnaeon** [kubernetes/kubeadm#2068]
## What keywords did you search in kubeadm issues before filing this one?

`apiserver`, `CreateContainerError`

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):

```
kubeadm version: &version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:01:11Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:

* Arch Linux
* 2 CPUs
* 4 GB of memory
* Single-node control plane cluster

Docker info.

```
[mnikolov@k8s-node03 ~]$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 31
  Running: 14
  Paused: 0
  Stopped: 17
 Images: 11
 Server Version: 19.03.8-ce
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d76c121f76a5fc8a462dc64594aea72fe18e1178.m
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.5.10-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.845GiB
 Name: k8s-node03
 ID: FCJY:KLLE:P5WP:T7CZ:AYG3:32DE:KJJV:HW5W:YONV:M7EB:DE5H:AQFH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- **Kubernetes version** (use `kubectl version`):

```
[mnikolov@k8s-node03 ~]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

- **Cloud provider or hardware configuration**:

* 2 CPUs
* 4 GB of memory
* vSphere VM

- **OS** (e.g. from /etc/os-release):

* Arch Linux VM.

```
[mnikolov@k8s-node03 ~]$ uname -a
Linux k8s-node03 5.5.10-arch1-1 #1 SMP PREEMPT Wed, 18 Mar 2020 08:40:35 +0000 x86_64 GNU/Linux
```

- **Kernel** (e.g. `uname -a`):

```
[mnikolov@k8s-node03 ~]$ uname -a
Linux k8s-node03 5.5.10-arch1-1 #1 SMP PREEMPT Wed, 18 Mar 2020 08:40:35 +0000 x86_64 GNU/Linux
```

- **Others**:

## What happened?

Boostrapped a single-node Kubernetes cluster using `kubeadm` according to the official documentation [here](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/)

```
[mnikolov@k8s-node03 ~]$ sudo kubeadm init --pod-network-cidr=10.1.16.0/20
```

The output from `kubeadm` command is below.

```
W0322 18:15:43.374769   11591 validation.go:28] Cannot validate kube-proxy config - no validator is available
W0322 18:15:43.374852   11591 validation.go:28] Cannot validate kubelet config - no validator is available
[init] Using Kubernetes version: v1.17.4
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
[certs] Using certificateDir folder "/etc/kubernetes/pki"
[certs] Generating "ca" certificate and key
[certs] Generating "apiserver" certificate and key
[certs] apiserver serving cert is signed for DNS names [k8s-node03 kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [10.96.0.1 192.168.88.227]
[certs] Generating "apiserver-kubelet-client" certificate and key
[certs] Generating "front-proxy-ca" certificate and key
[certs] Generating "front-proxy-client" certificate and key
[certs] Generating "etcd/ca" certificate and key
[certs] Generating "etcd/server" certificate and key
[certs] etcd/server serving cert is signed for DNS names [k8s-node03 localhost] and IPs [192.168.88.227 127.0.0.1 ::1]
[certs] Generating "etcd/peer" certificate and key
[certs] etcd/peer serving cert is signed for DNS names [k8s-node03 localhost] and IPs [192.168.88.227 127.0.0.1 ::1]
[certs] Generating "etcd/healthcheck-client" certificate and key
[certs] Generating "apiserver-etcd-client" certificate and key
[certs] Generating "sa" key and public key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Writing "admin.conf" kubeconfig file
[kubeconfig] Writing "kubelet.conf" kubeconfig file
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
W0322 18:16:25.379198   11591 manifests.go:214] the default kube-apiserver authorization-mode is "Node,RBAC"; using "Node,RBAC"
[control-plane] Creating static Pod manifest for "kube-scheduler"
W0322 18:16:25.379957   11591 manifests.go:214] the default kube-apiserver authorization-mode is "Node,RBAC"; using "Node,RBAC"
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[apiclient] All control plane components are healthy after 34.502368 seconds
[upload-config] Storing the configuration used in ConfigMap "kubeadm-config" in the "kube-system" Namespace
[kubelet] Creating a ConfigMap "kubelet-config-1.17" in namespace kube-system with the configuration for the kubelets in the cluster
[upload-certs] Skipping phase. Please see --upload-certs
[mark-control-plane] Marking the node k8s-node03 as control-plane by adding the label "node-role.kubernetes.io/master=''"
[mark-control-plane] Marking the node k8s-node03 as control-plane by adding the taints [node-role.kubernetes.io/master:NoSchedule]
[bootstrap-token] Using token: oh1s10.529hxnlealiz9qyd
[bootstrap-token] Configuring bootstrap tokens, cluster-info ConfigMap, RBAC Roles
[bootstrap-token] configured RBAC rules to allow Node Bootstrap tokens to post CSRs in order for nodes to get long term certificate credentials
[bootstrap-token] configured RBAC rules to allow the csrapprover controller automatically approve CSRs from a Node Bootstrap Token
[bootstrap-token] configured RBAC rules to allow certificate rotation for all node client certificates in the cluster
[bootstrap-token] Creating the "cluster-info" ConfigMap in the "kube-public" namespace
[kubelet-finalize] Updating "/etc/kubernetes/kubelet.conf" to point to a rotatable kubelet client certificate and key
[addons] Applied essential addon: CoreDNS
[addons] Applied essential addon: kube-proxy

Your Kubernetes control-plane has initialized successfully!

To start using your cluster, you need to run the following as a regular user:

  mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config

You should now deploy a pod network to the cluster.
Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
  https://kubernetes.io/docs/concepts/cluster-administration/addons/

Then you can join any number of worker nodes by running the following on each as root:

kubeadm join 192.168.88.227:6443 --token oh1s10.529hxnlealiz9qyd \
    --discovery-token-ca-cert-hash sha256:4d495ad293190669413dbb3a4ba21cd5c47f760d0129127a95c3ba45e2312258
```

Executed the next steps as suggested from the output.

Then did this.

```
  mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config
```

Installed Calico CNI. The `calico.yaml` file uses `10.1.16.0/20` CIDR for the pod network.

```
[mnikolov@k8s-node03 ~]$ kubectl apply -f calico.yaml
configmap/calico-config created
customresourcedefinition.apiextensions.k8s.io/felixconfigurations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ipamblocks.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/blockaffinities.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ipamhandles.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ipamconfigs.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/bgppeers.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/bgpconfigurations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ippools.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/hostendpoints.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/clusterinformations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/globalnetworkpolicies.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/globalnetworksets.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/networkpolicies.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/networksets.crd.projectcalico.org created
clusterrole.rbac.authorization.k8s.io/calico-kube-controllers created
clusterrolebinding.rbac.authorization.k8s.io/calico-kube-controllers created
clusterrole.rbac.authorization.k8s.io/calico-node created
clusterrolebinding.rbac.authorization.k8s.io/calico-node created
daemonset.apps/calico-node created
serviceaccount/calico-node created
deployment.apps/calico-kube-controllers created
serviceaccount/calico-kube-controllers created
```

Removed taints on the node.

```
[mnikolov@k8s-node03 ~]$ kubectl taint nodes --all node-role.kubernetes.io/master-
node/k8s-node03 untainted
```

Verified that I can see my node is ready.

```
[mnikolov@k8s-node03 ~]$ kubectl get nodes
NAME         STATUS   ROLES    AGE     VERSION
k8s-node03   Ready    master   2m56s   v1.17.4
[mnikolov@k8s-node03 ~]$
```

All pods are running as well.

```
[mnikolov@k8s-node03 ~]$ kubectl get pods --all-namespaces=true
NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
kube-system   calico-kube-controllers-5b644bc49c-jq74p   1/1     Running   0          111s
kube-system   calico-node-pq2md                          1/1     Running   0          111s
kube-system   coredns-6955765f44-ctbdx                   1/1     Running   0          2m58s
kube-system   coredns-6955765f44-kfh2x                   1/1     Running   0          2m58s
kube-system   etcd-k8s-node03                            1/1     Running   0          2m53s
kube-system   kube-apiserver-k8s-node03                  1/1     Running   0          2m53s
kube-system   kube-controller-manager-k8s-node03         1/1     Running   0          2m53s
kube-system   kube-proxy-8hnht                           1/1     Running   0          2m57s
kube-system   kube-scheduler-k8s-node03                  1/1     Running   0          2m53s
```

Everything has been setup correctly and working fine.

However, *after a reboot (or a couple of reboots) of the node* my pods don't seem healthy.

```
[mnikolov@k8s-node03 ~]$ kubectl get pods --all-namespaces=true
NAMESPACE     NAME                                       READY   STATUS                 RESTARTS   AGE
kube-system   calico-kube-controllers-5b644bc49c-jq74p   1/1     Running                2          30m
kube-system   calico-node-pq2md                          0/1     Completed              1          30m
kube-system   coredns-6955765f44-ctbdx                   1/1     Running                2          32m
kube-system   coredns-6955765f44-kfh2x                   1/1     Running                2          32m
kube-system   etcd-k8s-node03                            1/1     Running                4          31m
kube-system   kube-apiserver-k8s-node03                  0/1     CreateContainerError   2          31m
kube-system   kube-controller-manager-k8s-node03         1/1     Running                2          31m
kube-system   kube-proxy-8hnht                           0/1     Error                  1          32m
kube-system   kube-scheduler-k8s-node03                  1/1     Running                2          31m
```

These are the docker containers running on the node.

```
[mnikolov@k8s-node03 ~]$ docker ps
CONTAINER ID        IMAGE                  COMMAND                  CREATED                  STATUS                  PORTS               NAMES
08f32df88f41        303ce5db0e90           "etcd --advertise-cl…"   Less than a second ago   Up Less than a second                       k8s_etcd_etcd-k8s-node03_kube-system_6277a52921e8e92f54e82892b6c69df6_4
ede600f2d233        5db16c1c7aff           "kube-scheduler --au…"   Less than a second ago   Up Less than a second                       k8s_kube-scheduler_kube-scheduler-k8s-node03_kube-system_d4d13becd444ee4a984c5c68b2a69ffd_2
536938db25d7        7f997fcf3e94           "kube-controller-man…"   Less than a second ago   Up Less than a second                       k8s_kube-controller-manager_kube-controller-manager-k8s-node03_kube-system_f4c2904e140d045ccf0b4dceb2946e03_2
7543fc993647        k8s.gcr.io/pause:3.1   "/pause"                 Less than a second ago   Up Less than a second                       k8s_POD_kube-apiserver-k8s-node03_kube-system_6a0284976259421857420f734ede268e_2
d0331321f894        k8s.gcr.io/pause:3.1   "/pause"                 Less than a second ago   Up Less than a second                       k8s_POD_kube-controller-manager-k8s-node03_kube-system_f4c2904e140d045ccf0b4dceb2946e03_2
f793499d1bb7        k8s.gcr.io/pause:3.1   "/pause"                 Less than a second ago   Up Less than a second                       k8s_POD_kube-scheduler-k8s-node03_kube-system_d4d13becd444ee4a984c5c68b2a69ffd_2
5ce453a02e86        k8s.gcr.io/pause:3.1   "/pause"                 Less than a second ago   Up Less than a second                       k8s_POD_etcd-k8s-node03_kube-system_6277a52921e8e92f54e82892b6c69df6_2
c2f1fa67fb9a        6dec7cfde1e5           "/usr/local/bin/kube…"   1 second ago             Up Less than a second                       k8s_kube-proxy_kube-proxy-8hnht_kube-system_b50123a6-c6f8-4f17-a17b-db5d70eb3a1c_2
3a4e273ca8ac        k8s.gcr.io/pause:3.1   "/pause"                 1 second ago             Up Less than a second                       k8s_POD_calico-node-pq2md_kube-system_171413c5-1fb9-4c13-ad61-4ca7088d9c29_2
7d070b5e2841        k8s.gcr.io/pause:3.1   "/pause"                 1 second ago             Up Less than a second                       k8s_POD_kube-proxy-8hnht_kube-system_b50123a6-c6f8-4f17-a17b-db5d70eb3a1c_2
40744dbd2986        9e897df2f2af           "/usr/bin/kube-contr…"   21 minutes ago           Up 21 minutes                               k8s_calico-kube-controllers_calico-kube-controllers-5b644bc49c-jq74p_kube-system_f04ea78e-c106-4632-a8a2-44905c5df971_2
f7b0a6083149        k8s.gcr.io/pause:3.1   "/pause"                 21 minutes ago           Up 21 minutes                               k8s_POD_calico-kube-controllers-5b644bc49c-jq74p_kube-system_f04ea78e-c106-4632-a8a2-44905c5df971_8
64eeff44d5f8        70f311871ae1           "/coredns -conf /etc…"   21 minutes ago           Up 21 minutes                               k8s_coredns_coredns-6955765f44-ctbdx_kube-system_3f1f942d-2d44-4e1c-b48a-3fb5da9d4834_2
8ab74918c6f7        k8s.gcr.io/pause:3.1   "/pause"                 21 minutes ago           Up 21 minutes                               k8s_POD_coredns-6955765f44-ctbdx_kube-system_3f1f942d-2d44-4e1c-b48a-3fb5da9d4834_9
332211b5b926        70f311871ae1           "/coredns -conf /etc…"   21 minutes ago           Up 21 minutes                               k8s_coredns_coredns-6955765f44-kfh2x_kube-system_553e0ab9-5a48-4748-8df8-b6fd895e4df5_2
a6a2f0221ef2        k8s.gcr.io/pause:3.1   "/pause"                 21 minutes ago           Up 21 minutes                               k8s_POD_coredns-6955765f44-kfh2x_kube-system_553e0ab9-5a48-4748-8df8-b6fd895e4df5_8
730e348467da        2e1ba57fe95a           "kube-apiserver --ad…"   22 minutes ago           Up 22 minutes                               k8s_kube-apiserver_kube-apiserver-k8s-node03_kube-system_6a0284976259421857420f734ede268e_3
```

This is the log of `kube-apiserver` pod.

```
[mnikolov@k8s-node03 ~]$ kubectl logs kube-apiserver-k8s-node03 -n kube-system
Flag --insecure-port has been deprecated, This flag will be removed in a future version.
I0322 19:19:07.770204       1 server.go:596] external host was not specified, using 192.168.88.227
I0322 19:19:07.773551       1 server.go:150] Version: v1.17.4
I0322 19:19:08.251732       1 plugins.go:158] Loaded 11 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,MutatingAdmissionWebhook,RuntimeClass.
I0322 19:19:08.251793       1 plugins.go:161] Loaded 7 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,ValidatingAdmissionWebhook,RuntimeClass,ResourceQuota.
I0322 19:19:08.254751       1 plugins.go:158] Loaded 11 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,MutatingAdmissionWebhook,RuntimeClass.
I0322 19:19:08.254797       1 plugins.go:161] Loaded 7 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,ValidatingAdmissionWebhook,RuntimeClass,ResourceQuota.
I0322 19:19:08.264082       1 client.go:361] parsed scheme: "endpoint"
I0322 19:19:08.264205       1 endpoint.go:68] ccResolverWrapper: sending new addresses to cc: [{https://127.0.0.1:2379 0  <nil>}]
W0322 19:19:08.265649       1 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused". Reconnecting...
I0322 19:19:09.249435       1 client.go:361] parsed scheme: "endpoint"
I0322 19:19:09.249467       1 endpoint.go:68] ccResolverWrapper: sending new addresses to cc: [{https://127.0.0.1:2379 0  <nil>}]
W0322 19:19:09.249867       1 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused". Reconnecting...
W0322 19:19:09.266060       1 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused". Reconnecting...
W0322 19:19:10.250366       1 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused". Reconnecting...
W0322 19:19:10.852208       1 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused". Reconnecting...
W0322 19:19:12.027149       1 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused". Reconnecting...
W0322 19:19:13.806110       1 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused". Reconnecting...
W0322 19:19:14.337742       1 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused". Reconnecting...
W0322 19:19:17.730967       1 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused". Reconnecting...
W0322 19:19:17.822367       1 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused". Reconnecting...
W0322 19:19:24.878651       1 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused". Reconnecting...
W0322 19:19:24.944348       1 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused". Reconnecting...
panic: context deadline exceeded

goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/registry/customresourcedefinition.NewREST(0xc00057c930, 0x4f6dd40, 0xc0001a5e60, 0xc0001738a8)
	/workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/registry/customresourcedefinition/etcd.go:56 +0x3c1
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver.completedConfig.New(0xc000bfb560, 0xc00045bdc8, 0x502e420, 0x75682f0, 0x10, 0x0, 0x0)
	/workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go:147 +0x152b
k8s.io/kubernetes/cmd/kube-apiserver/app.createAPIExtensionsServer(0xc00045bdc0, 0x502e420, 0x75682f0, 0x0, 0x4f6d9e0, 0xc000237840)
	/workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/apiextensions.go:99 +0x59
k8s.io/kubernetes/cmd/kube-apiserver/app.CreateServerChain(0xc000591b80, 0xc000096fc0, 0x449aeca, 0xc, 0xc000731c48)
	/workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:183 +0x292
k8s.io/kubernetes/cmd/kube-apiserver/app.Run(0xc000591b80, 0xc000096fc0, 0x0, 0x0)
	/workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:152 +0x101
k8s.io/kubernetes/cmd/kube-apiserver/app.NewAPIServerCommand.func1(0xc000121b80, 0xc000574680, 0x0, 0x1a, 0x0, 0x0)
	/workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:119 +0x104
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc000121b80, 0xc0000ba010, 0x1a, 0x1b, 0xc000121b80, 0xc0000ba010)
	/workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:826 +0x460
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000121b80, 0x15feb6788d4c0419, 0x754a340, 0xc00006a750)
	/workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:864
main.main()
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/apiserver.go:43 +0xcd
```

And this is the spec for the pod.

```
[mnikolov@k8s-node03 ~]$ kubectl describe pod kube-apiserver-k8s-node03 -n kube-system
Name:                 kube-apiserver-k8s-node03
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 k8s-node03/192.168.88.227
Start Time:           Sun, 22 Mar 2020 18:29:09 +0200
Labels:               component=kube-apiserver
                      tier=control-plane
Annotations:          kubernetes.io/config.hash: 6a0284976259421857420f734ede268e
                      kubernetes.io/config.mirror: 6a0284976259421857420f734ede268e
                      kubernetes.io/config.seen: 2020-03-22T18:17:01.388382691+02:00
                      kubernetes.io/config.source: file
Status:               Running
IP:                   192.168.88.227
IPs:
  IP:           192.168.88.227
Controlled By:  Node/k8s-node03
Containers:
  kube-apiserver:
    Container ID:  docker://271409339ab1972f99a80bfa8f55634257fa0cd4159e0084de6e024a1acbaee5
    Image:         k8s.gcr.io/kube-apiserver:v1.17.4
    Image ID:      docker-pullable://k8s.gcr.io/kube-apiserver@sha256:bbcec0b4ee3ef6c0f0a27c028b3a44234863f6e783a71c79cb5e651f82e992c8
    Port:          <none>
    Host Port:     <none>
    Command:
      kube-apiserver
      --advertise-address=192.168.88.227
      --allow-privileged=true
      --authorization-mode=Node,RBAC
      --client-ca-file=/etc/kubernetes/pki/ca.crt
      --enable-admission-plugins=NodeRestriction
      --enable-bootstrap-token-auth=true
      --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt
      --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt
      --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key
      --etcd-servers=https://127.0.0.1:2379
      --insecure-port=0
      --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
      --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
      --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
      --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
      --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
      --requestheader-allowed-names=front-proxy-client
      --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
      --requestheader-extra-headers-prefix=X-Remote-Extra-
      --requestheader-group-headers=X-Remote-Group
      --requestheader-username-headers=X-Remote-User
      --secure-port=6443
      --service-account-key-file=/etc/kubernetes/pki/sa.pub
      --service-cluster-ip-range=10.96.0.0/12
      --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
      --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
    State:          Waiting
      Reason:       CreateContainerError
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Sun, 22 Mar 2020 21:19:07 +0200
      Finished:     Sun, 22 Mar 2020 21:19:28 +0200
    Ready:          False
    Restart Count:  2
    Requests:
      cpu:        250m
    Liveness:     http-get https://192.168.88.227:6443/healthz delay=15s timeout=15s period=10s #success=1 #failure=8
    Environment:  <none>
    Mounts:
      /etc/ca-certificates from etc-ca-certificates (ro)
      /etc/kubernetes/pki from k8s-certs (ro)
      /etc/ssl/certs from ca-certs (ro)
      /usr/share/ca-certificates from usr-share-ca-certificates (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  ca-certs:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/ssl/certs
    HostPathType:  DirectoryOrCreate
  etc-ca-certificates:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/ca-certificates
    HostPathType:  DirectoryOrCreate
  k8s-certs:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/pki
    HostPathType:  DirectoryOrCreate
  usr-share-ca-certificates:
    Type:          HostPath (bare host directory volume)
    Path:          /usr/share/ca-certificates
    HostPathType:  DirectoryOrCreate
QoS Class:         Burstable
Node-Selectors:    <none>
Tolerations:       :NoExecute
Events:
  Type     Reason          Age                     From                 Message
  ----     ------          ----                    ----                 -------
  Normal   Created         5m51s                   kubelet, k8s-node03  Created container kube-apiserver
  Normal   Started         5m51s                   kubelet, k8s-node03  Started container kube-apiserver
  Warning  Failed          3m29s (x11 over 5m20s)  kubelet, k8s-node03  Error: Error response from daemon: Conflict. The container name "/k8s_kube-apiserver_kube-apiserver-k8s-node03_kube-system_6a0284976259421857420f734ede268e_3" is already in use by container "730e348467da2eebe8c10701895fed834243c16646e24b720327f3ed0ef555d2". You have to remove (or rename) that container to be able to reuse that name.
  Normal   Pulled          35s (x25 over 5m51s)    kubelet, k8s-node03  Container image "k8s.gcr.io/kube-apiserver:v1.17.4" already present on machine
  Normal   SandboxChanged  <invalid>               kubelet, k8s-node03  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled          <invalid>               kubelet, k8s-node03  Container image "k8s.gcr.io/kube-apiserver:v1.17.4" already present on machine
  Normal   Created         <invalid>               kubelet, k8s-node03  Created container kube-apiserver
  Normal   Started         <invalid>               kubelet, k8s-node03  Started container kube-apiserver
  Warning  Unhealthy       <invalid>               kubelet, k8s-node03  Liveness probe failed: HTTP probe failed with statuscode: 500
 ```

## What you expected to happen?

After a reboot all pods are running correctly.

## How to reproduce it (as minimally and precisely as possible)?

Please refer to the steps described in "What happened" section.

**Comment by dnaeon** [comment]
Note that removing the offending Docker container and deleting the `kube-apiserver` pod manually fixes the issue, but I'd like to understand how to fix this permanently, so I don't have to workaround this manually after each node reboot.

**Comment by neolit123** [comment]
> panic: context deadline exceeded

hi, in any case the kube-apiserver should not be panicing.
please close this ticket and open it in the kubernetes/kubernetes repository, while tagging it with `/sig api-machinery` and `/kind bug`. this will allow the owners of the api-server and etcd integration to investigate the panic when they do triage.

thanks.

**Comment by dnaeon** [comment]
@neolit123 submitted a new one here:

* https://github.com/kubernetes/kubernetes/issues/89368

Thanks!
