### ISSUE TITLE
kubeadm and kubelet seems didn't work with containerd-only setup ..  

### ISSUE THREAD

**Issue by fragtom** [kubernetes/kubeadm#2293]
## Is this a request for help?
This issue is a description of unexpected behaviour kubeadm / kubelet using containerd

## What keywords did you search in kubeadm issues before filing this one?
kubeadm init phase kubelet-start, -cri-socket to containerd.socket

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version**:
v1.19.2 - kubeadm.x86_64 0:1.19.2-0
**kubelet version**:
v1.19.2 - kubelet.x86_64 0:1.19.2-

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
```
# cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.8 (Maipo)"
```
- **Kernel** (e.g. `uname -a`):
```
Linux expr-etcd1 3.10.0-1127.8.2.el7.x86_64 #1 SMP Thu May 7 19:30:37 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
```

## What happened?
kubeadm and kubelet didn't play well with using containerd (only) as CRI. Accordingly to Kubernetes documentation to setup [HA kubernetes stack using kubeadm](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/), and specific configuration with kubelet args, the kubelet didn't start, missing docker as runtime.

```
Sep 16 23:26:36 expr-etcd1.node  kubelet[522]: F0916 23:26:36.309914     522 server.go:265] failed to run Kubelet: failed to get docker version: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

[configure-kubelets-using-kubeadm](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/kubelet-integration/#configure-kubelets-using-kubeadm)

## What you expected to happen?

Expect, that kubeadm/kubelet play well without docker.

## How to reproduce it (as minimally and precisely as possible)?

set config file providing to kubeadm init phase and provide KUBELET_EXTRA_ARGS in /etc/systemd/system/kubelet.service.d/0-containerd.conf
```
[Service]
Environment="KUBELET_EXTRA_ARGS=--container-runtime=remote --container-runtime-endpoint=unix:///run/containerd/containerd.sock"
```
set config InitConfiguration and KubeletConfiguration
```
# cat /root/kubeletcfg.yaml 
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    runtime-cgroups: /system.slice/containerd.service
    kubelet-cgroups: /systemd/system.slice
    container-runtime: remote  
    container-runtime-endpoint: unix:///run/containerd/containerd.sock
    cgroup-driver: systemd
  criSocket: /var/run/containerd/containerd.sock
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
maxPods: 90
evictionHard:
  memory.available: "1024Mi"
  nodefs.available: "10%"
```

and then run following
```
kubeadm init phase kubelet-start --config=/root/kubeletcfg.yaml
```

also tried to rund with explicitly providing cri-socket.
```
kubeadm init phase kubelet-start --config=/root/kubeletcfg.yaml --cri-socket="unix:///run/containerd/containerd.sock"
```

kubelet starts and immediately breaks, kubelet.service failed.
```
-- Unit kubelet.service has finished starting up.
-- 
-- The start-up result is done.
Sep 16 23:26:31 expr-etcd1.node kubelet[522]: I0916 23:26:31.292957     522 server.go:411] Version: v1.19.1
Sep 16 23:26:31 expr-etcd1.node kubelet[522]: W0916 23:26:31.293503     522 server.go:553] standalone mode, no API client
Sep 16 23:26:36 expr-etcd1.node kubelet[522]: W0916 23:26:36.305730     522 nvidia.go:61] NVIDIA GPU metrics will not be available: no NVIDIA devices found
Sep 16 23:26:36 expr-etcd1.node kubelet[522]: W0916 23:26:36.309042     522 server.go:468] No api server defined - no events will be sent to API server.
Sep 16 23:26:36 expr-etcd1.node kubelet[522]: I0916 23:26:36.309076     522 server.go:640] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
Sep 16 23:26:36 expr-etcd1.node kubelet[522]: I0916 23:26:36.309428     522 container_manager_linux.go:276] container manager verified user specified cgroup-root exists: []
Sep 16 23:26:36 expr-etcd1.node kubelet[522]: I0916 23:26:36.309445     522 container_manager_linux.go:281] Creating Container Manager object based on Node Config: {RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: ContainerRuntime:docker CgroupsPerQOS:true CgroupRoot:/ CgroupDriver:cgroupfs KubeletRootDir:/var/lib/kubelet ProtectKernelDefaults:false NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: ReservedSystemCPUs: EnforceNodeAllocatable:map[pods:{}] KubeReserved:map[] SystemReserved:map[] HardEvictionThresholds:[{Signal:memory.available Operator:LessThan Value:{Quantity:100Mi Percentage:0} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.1} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.inodesFree Operator:LessThan Value:{Quantity:<nil> Percentage:0.05} GracePeriod:0s MinReclaim:<nil>} {Signal:imagefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.15} GracePeriod:0s MinReclaim:<nil>}]} QOSReserved:map[] ExperimentalCPUManagerPolicy:none ExperimentalCPUManagerReconcilePeriod:10s ExperimentalPodPidsLimit:-1 EnforceCPULimits:true CPUCFSQuotaPeriod:100ms ExperimentalTopologyManagerPolicy:none}
Sep 16 23:26:36 expr-etcd1.node kubelet[522]: I0916 23:26:36.309626     522 topology_manager.go:126] [topologymanager] Creating topology manager with none policy
Sep 16 23:26:36 expr-etcd1.node kubelet[522]: I0916 23:26:36.309637     522 container_manager_linux.go:311] [topologymanager] Initializing Topology Manager with none policy
Sep 16 23:26:36 expr-etcd1.node kubelet[522]: I0916 23:26:36.309642     522 container_manager_linux.go:316] Creating device plugin manager: true
Sep 16 23:26:36 expr-etcd1.node kubelet[522]: I0916 23:26:36.309737     522 client.go:77] Connecting to docker on unix:///var/run/docker.sock
Sep 16 23:26:36 expr-etcd1 kubelet[522]: I0916 23:26:36.309751     522 client.go:94] Start docker client with request timeout=2m0s
Sep 16 23:26:36 expr-etcd1.node  kubelet[522]: F0916 23:26:36.309914     522 server.go:265] failed to run Kubelet: failed to get docker version: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Sep 16 23:26:36 expr-etcd1.node kubelet[522]: goroutine 1 [running]:
Sep 16 23:26:36 expr-etcd1.node kubelet[522]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc000010001, 0xc00044b680, 0xc4, 0x20e)
Sep 16 23:26:36 expr-etcd1.node kubelet[522]: /workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:996 +0xb9

```

## Anything else we need to know?

```
# kubeadm config print init-defaults --component-configs KubeletConfiguration
W0916 23:42:58.277631    2413 kubelet.go:200] cannot automatically set CgroupDriver when starting the Kubelet: cannot execute 'docker info -f {{.CgroupDriver}}': exit status 2
W0916 23:42:58.281614    2413 configset.go:348] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
W0916 23:42:58.378338    2413 kubelet.go:200] cannot automatically set CgroupDriver when starting the Kubelet: cannot execute 'docker info -f {{.CgroupDriver}}': exit status 2
W0916 23:42:58.381591    2413 configset.go:348] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
apiVersion: kubeadm.k8s.io/v1beta2
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: abcdef.0123456789abcdef
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 1.2.3.4
  bindPort: 6443
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  name: expr-etcd1.node
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
---
apiServer:
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta2
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controllerManager: {}
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: k8s.gcr.io
kind: ClusterConfiguration
kubernetesVersion: v1.19.0
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
scheduler: {}
---
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 0s
    enabled: true
  x509:
    clientCAFile: /etc/kubernetes/pki/ca.crt
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 0s
    cacheUnauthorizedTTL: 0s
clusterDNS:
- 10.96.0.10
clusterDomain: cluster.local
cpuManagerReconcilePeriod: 0s
evictionPressureTransitionPeriod: 0s
fileCheckFrequency: 0s
healthzBindAddress: 127.0.0.1
healthzPort: 10248
httpCheckFrequency: 0s
imageMinimumGCAge: 0s
kind: KubeletConfiguration
logging: {}
nodeStatusReportFrequency: 0s
nodeStatusUpdateFrequency: 0s
rotateCertificates: true
runtimeRequestTimeout: 0s
staticPodPath: /etc/kubernetes/manifests
streamingConnectionIdleTimeout: 0s
syncFrequency: 0s
volumeStatsAggPeriod: 0s
```

**Comment by neolit123** [comment]
> kubeadm and kubelet didn't play well with using containerd (only) as CRI. Accordingly to Kubernetes documentation to setup HA kubernetes stack using kubeadm, and specific configuration with kubelet args, the kubelet didn't start, missing docker as runtime.

we have e2e tests here using containerd only (no docker daemon running):
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all

also i tested the same setup the other day on separate VMs debugging a separate issue. so standalone containerd does work.

```
-- Unit kubelet.service has finished starting up.
-- 
-- The start-up result is done.
Sep 16 23:26:31 expr-etcd1.node kubelet[522]: I0916 23:26:31.292957     522 server.go:411] Version: v1.19.1
Sep 16 23:26:31 expr-etcd1.node kubelet[522]: W0916 23:26:31.293503     522 server.go:553] standalone mode, no API client
Sep 16 23:26:36 expr-etcd1.node kubelet[522]: W0916 23:26:36.305730     522 nvidia.go:61] NVIDIA GPU metrics will not be available: no NVIDIA devices found
Sep 16 23:26:36 expr-etcd1.node kubelet[522]: W0916 23:26:36.309042     522 server.go:468] No api server defined - no events will be sent to API server.
Sep 16 23:26:36 expr-etcd1.node kubelet[522]: I0916 23:26:36.309076     522 server.go:640] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
Sep 16 23:26:36 expr-etcd1.node kubelet[522]: I0916 23:26:36.309428     522 container_manager_linux.go:276] container manager verified user specified cgroup-root exists: []
Sep 16 23:26:36 expr-etcd1.node kubelet[522]: I0916 23:26:36.309445     522 container_manager_linux.go:281] Creating Container Manager object based on Node Config: {RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: ContainerRuntime:docker CgroupsPerQOS:true CgroupRoot:/ CgroupDriver:cgroupfs KubeletRootDir:/var/lib/kubelet ProtectKernelDefaults:false NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: ReservedSystemCPUs: EnforceNodeAllocatable:map[pods:{}] KubeReserved:map[] SystemReserved:map[] HardEvictionThresholds:[{Signal:memory.available Operator:LessThan Value:{Quantity:100Mi Percentage:0} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.1} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.inodesFree Operator:LessThan Value:{Quantity:<nil> Percentage:0.05} GracePeriod:0s MinReclaim:<nil>} {Signal:imagefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.15} GracePeriod:0s MinReclaim:<nil>}]} QOSReserved:map[] ExperimentalCPUManagerPolicy:none ExperimentalCPUManagerReconcilePeriod:10s ExperimentalPodPidsLimit:-1 EnforceCPULimits:true CPUCFSQuotaPeriod:100ms ExperimentalTopologyManagerPolicy:none}
Sep 16 23:26:36 expr-etcd1.node kubelet[522]: I0916 23:26:36.309626     522 topology_manager.go:126] [topologymanager] Creating topology manager with none policy
Sep 16 23:26:36 expr-etcd1.node kubelet[522]: I0916 23:26:36.309637     522 container_manager_linux.go:311] [topologymanager] Initializing Topology Manager with none policy
Sep 16 23:26:36 expr-etcd1.node kubelet[522]: I0916 23:26:36.309642     522 container_manager_linux.go:316] Creating device plugin manager: true
Sep 16 23:26:36 expr-etcd1.node kubelet[522]: I0916 23:26:36.309737     522 client.go:77] Connecting to docker on unix:///var/run/docker.sock
Sep 16 23:26:36 expr-etcd1 kubelet[522]: I0916 23:26:36.309751     522 client.go:94] Start docker client with request timeout=2m0s
Sep 16 23:26:36 expr-etcd1.node  kubelet[522]: F0916 23:26:36.309914     522 server.go:265] failed to run Kubelet: failed to get docker version: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Sep 16 23:26:36 expr-etcd1.node kubelet[522]: goroutine 1 [running]:
Sep 16 23:26:36 expr-etcd1.node kubelet[522]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc000010001, 0xc00044b680, 0xc4, 0x20e)
Sep 16 23:26:36 expr-etcd1.node kubelet[522]: /workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:996 +0xb9
```

when this happens are you sure the kubelet is receiving the right flags? i doubt it is..
you can check that with something like `ps -p [kubelet-PID] -o args`.

> set config file providing to kubeadm init phase and provide KUBELET_EXTRA_ARGS in /etc/systemd/system/kubelet.service.d/0-containerd.conf

we don't recommend doing that in the kubeadm docs.
kubeadm does the same dynamically by writing the `/var/lib/kubelet/kubeadm-flags.env` file during kubeadm init/join execution, so i wonder if something is conflicting here.

>  kubeadm config print init-defaults --component-configs KubeletConfiguration

printing the defaults does not seem relevant here.


/triage support

**Comment by neolit123** [comment]
> kubeadm init phase kubelet-start --config=/root/kubeletcfg.yaml

looking at the code, i don't see potential flows around executing the phase:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/phases/init/kubelet.go

**Comment by fragtom** [comment]
you are right, you do not recommend to use dropin to kubelet, sorry for that.

I wrote this /etc/systemd/system/kubelet.service.d/0-containerd.conf out of sheer desperation, after lot of tries.
this is the output after kubeadm init.


# cat /var/lib/kubelet/kubeadm-flags.env
```
KUBELET_KUBEADM_ARGS="--cgroup-driver=systemd --container-runtime=remote --container-runtime-endpoint=unix:///run/containerd/containerd.sock --kubelet-cgroups=/systemd/system.slice --runtime-cgroups=/system.slice/containerd.service"
```

But this should work with kubeadm flags, I expect. I cannot see args on kubelet, the process fails and is not visible in process list.

**Comment by neolit123** [comment]
my speculation is that the `/var/lib/kubelet/kubeadm-flags.env` settings are not being passed to the kubelet for some reason and it defaults to the docker socket.

i'd try removing `kubelet.service.d/0-containerd.conf`.

you could also pass `--v=4` to the kubelet to see what flag values it receives.

**Comment by fragtom** [comment]
cleanup my setup, removed 0-containerd, checked kubeadm-flags.env. But run in other issue.

regarding the deprecated message of kubelet `--cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's ... ` did this like [configure-cgroup-driver](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#configure-cgroup-driver-used-by-kubelet-on-control-plane-node).

use this config
```
cat << EOF > /root/kubeletcfg.yaml
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    runtime-cgroups: /system.slice/containerd.service
    container-runtime: remote  
    container-runtime-endpoint: unix:///run/containerd/containerd.sock
    v: "4"
  criSocket: /var/run/containerd/containerd.sock
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
maxPods: 90
evictionHard:
  memory.available: "1024Mi"
  nodefs.available: "10%"
cgroupDriver: systemd
EOF
```


kubelet debug output is
```
Sep 17 09:21:33 expr-etcd1.node kubelet[24008]: I0917 09:21:33.784140   24008 flags.go:59] FLAG: --cgroup-driver="cgroupfs"
Sep 17 09:21:33 expr-etcd1.node kubelet[24008]: I0917 09:21:33.784145   24008 flags.go:59] FLAG: --cgroup-root=""
```

See following config.yaml was generated:
```
# cat /var/lib/kubelet/config.yaml
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 0s
    enabled: true
  x509:
    clientCAFile: /etc/kubernetes/pki/ca.crt
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 0s
    cacheUnauthorizedTTL: 0s
cgroupDriver: systemd
clusterDNS:
- 10.96.0.10
clusterDomain: cluster.local
cpuManagerReconcilePeriod: 0s
evictionHard:
  memory.available: 1024Mi
  nodefs.available: 10%
evictionPressureTransitionPeriod: 0s
fileCheckFrequency: 0s
healthzBindAddress: 127.0.0.1
healthzPort: 10248
httpCheckFrequency: 0s
imageMinimumGCAge: 0s
kind: KubeletConfiguration
logging: {}
maxPods: 90
nodeStatusReportFrequency: 0s
nodeStatusUpdateFrequency: 0s
rotateCertificates: true
runtimeRequestTimeout: 0s
staticPodPath: /etc/kubernetes/manifests
streamingConnectionIdleTimeout: 0s
syncFrequency: 0s
volumeStatsAggPeriod: 0s
```

It seems, kubelet didn't complain about cgroup, containerd... cool.

But didn't start-up with fatal error:
```
F0917 09:21:33.789325   24008 server.go:253] unable to load client CA file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory
```
didn't know why this is so.. thought, that etcd would not be relevant in `kubelet-start` phase. 

kubeadm init phase kubelet-start --config=/root/kubeletcfg.yaml

**Comment by neolit123** [comment]
After 1.19, kubeadm does the cgroup setup via KubeletConfiguration and
should not be passing the flags. Its fine as long as the cgroup driver
between CR and kubelet match.

Regarding the missing CA, you should call "init phase certs ca" before
starting the kubelet. If you look at the kubelet config it needs some files.

Closing since I don't see a bug here, but LMK if you have more questions.

/close

**Comment by fragtom** [comment]
using `kubeadm init phase certs ca` beforehand, the kubelet still fails.. 

relevant entries for authentication would like  this:
```
Sep 17 15:38:10 expr-control1.node kubelet[5603]: I0917 15:38:10.329947    5603 flags.go:59] FLAG: --authentication-token-webhook="false"
Sep 17 15:38:10 expr-control1.node kubelet[5603]: I0917 15:38:10.329951    5603 flags.go:59] FLAG: --authentication-token-webhook-cache-ttl="2m0s"
Sep 17 15:38:10 expr-control1.node kubelet[5603]: I0917 15:38:10.329956    5603 flags.go:59] FLAG: --authorization-mode="AlwaysAllow"
Sep 17 15:38:10 expr-control1.node kubelet[5603]: I0917 15:38:10.329961    5603 flags.go:59] FLAG: --authorization-webhook-cache-authorized-ttl="5m0s"
Sep 17 15:38:10 expr-control1.node kubelet[5603]: I0917 15:38:10.329966    5603 flags.go:59] FLAG: --authorization-webhook-cache-unauthorized-ttl="30s"
```

and then failing with
```
Sep 17 15:38:10 expr-control1.node kubelet[5603]: I0917 15:38:10.356454    5603 dynamic_cafile_content.go:129] Loaded a new CA Bundle and Verifier for "client-ca-bundle::/etc/kubernetes/pki/ca.crt"
Sep 17 15:38:10 expr-control1.node kubelet[5603]: F0917 15:38:10.356469    5603 server.go:265] failed to run Kubelet: no client provided, cannot use webhook authentication
Sep 17 15:38:10 expr-control1.node kubelet[5603]: goroutine 1 [running]:
Sep 17 15:38:10 expr-control1.node kubelet[5603]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc000010001, 0xc0008f80a0, 0x7a, 0x9e)
Sep 17 15:38:10 expr-control1.node kubelet[5603]: /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:996 +0xb9
...
```

didn't understand why this happens.. thanks for hinting me again..

**Comment by neolit123** [comment]
i'm trying to understand what is your use case.
can you explain why are you running the kubelet phase standalone and what you are trying to achieve?

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/kubelet-integration/

^ kubeadm assumes that you want to run the kubelet for Node bootstrapping purposes.

that's why it need always passes:
> Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf
--kubeconfig=/etc/kubernetes/kubelet.conf"

if you don't have some of the files that it needs it will error out....

so you could do:
```bash
# this will generate a CA 
kubeadm init phase certs ca
# this will generate client certificates and embed them in /etc/kubernetes/kubelet.conf
kubeadm init phase kubeconfig kubelet
# to start the kubelet with the embed client certificates, this will result in writing them to disk at /var/lib/kubelet/pki
kubeadm init phase kubelet-start
# to make /etc/kubernetes/kubelet.conf point to /var/lib/kubelet/pki
kubeadm init phase kubelet-finalize all
# start the kubelet again using the client certs on disk
kubeadm init phase kubelet-start all
```

alternatively you can extract the certs manually and only then call kubelet-start.

but again, not sure what you are trying to achieve.

**Comment by fragtom** [comment]
it drives me a little bit crazy, the workflow of [ha setup](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/) didn't work. 
In the past, it was successful with docker-ce, with this setup containerd only not. 

```
# ### Install required packages.
# yum install -y yum-utils device-mapper-persistent-data lvm2
# ## Install Docker CE.
# yum update && yum install -y --skip-broken docker-ce docker-ce-cli containerd.io

### yum install, update kubelet, kubeadm
yum install -y -q kubeadm kubelet kubectl containerd.io --disableexcludes=kubernetes
yum update -y -q kubeadm kubelet kubectl containerd.io 
# yum erase -y docker-ce docker-ce-cli

# change swap, iptables 
swapoff -a

cat > /etc/sysctl.d/k8s.conf <<EOF
net.bridge.bridge-nf-call-iptables  = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward                 = 1
EOF

# ### containerd
# containerd config default > /etc/containerd/config.toml

## use default containerd.toml, patch containerd to be set runtime_type = "io.containerd.runc.v2" 
## different to default /etc/containerd/config.toml 
....
      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
          runtime_type = "io.containerd.runc.v2"
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
            SystemdCgroup = true
...

cat > /etc/modules-load.d/containerd.conf <<EOF
overlay
br_netfilter
EOF

systemctl daemon-reload
systemctl enable --now containerd

# ### kubernetes repo
cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF

##### 
### kubelet configuration
#####
cat <<EOF > /root/kubeletcfg.yaml
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
nodeRegistration:
    kubeletExtraArgs:
        runtime-cgroups: /system.slice/containerd.service
        container-runtime: remote  
        container-runtime-endpoint: unix:///run/containerd/containerd.sock
        v: "4"
    criSocket: /var/run/containerd/containerd.sock
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
EOF

# ### kubeadm 
kubeadm config images pull --config=/root/kubeletcfg.yaml
```
so far, this is done on all machines.

To setup etcd cluster, I went through all the scripts, on the part '7. Create the static pod manifests' and start-up kubelet, fails.

following script runs on first machine.
```
# Update HOST0, HOST1, and HOST2 with the IPs or resolvable names of your hosts
export HOST0=172.19.209.193
export HOST1=172.19.209.194
export HOST2=172.19.209.195

ETCDHOSTS=(${HOST0} ${HOST1} ${HOST2} 
NAMES=("etcd1" "etcd2" "etcd3")

##### 
### etcd ha cluster configuration 
#####

for i in "${!ETCDHOSTS[@]}"; do
HOST=${ETCDHOSTS[$i]}
NAME=${NAMES[$i]}
mkdir -p /tmp/${HOST}
cat << EOF > /tmp/${HOST}/kubeadmcfg.yaml
apiVersion: "kubeadm.k8s.io/v1beta2"
kind: ClusterConfiguration
etcd:
    local:
        serverCertSANs:
        - "${HOST}"
        peerCertSANs:
        - "${HOST}"
        extraArgs:
            initial-cluster: ${NAMES[0]}=https://${ETCDHOSTS[0]}:2380,${NAMES[1]}=https://${ETCDHOSTS[1]}:2380,${NAMES[2]}=https://${ETCDHOSTS[2]}:2380
            initial-cluster-state: new
            name: ${NAME}
            listen-peer-urls: https://${HOST}:2380
            listen-client-urls: https://${HOST}:2379
            advertise-client-urls: https://${HOST}:2379
            initial-advertise-peer-urls: https://${HOST}:2380      
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
nodeRegistration:
    kubeletExtraArgs:
        runtime-cgroups: /system.slice/containerd.service
        container-runtime: remote  
        container-runtime-endpoint: unix:///run/containerd/containerd.sock
        v: "4"
    criSocket: /var/run/containerd/containerd.sock
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
maxPods: 90
cgroupDriver: systemd
EOF

done 

rm -f /root/kubeadmcfg.yaml
mv /tmp/${HOST0}/kubeadmcfg.yaml /root

## thanks kubeadm, that's awesome to gen ca
kubeadm init phase certs etcd-ca --config=/root/kubeadmcfg.yaml

## reverse order, keep ca.crt and ca.key in /etc/kubernetes/pki as is
for i in $(echo ${!ETCDHOSTS[@]}|rev); do
    HOST=${ETCDHOSTS[$i]}
    mkdir -p /tmp/${HOST}
    kubeadm init phase certs etcd-server --config=/tmp/${HOST}/kubeadmcfg.yaml
    kubeadm init phase certs etcd-peer --config=/tmp/${HOST}/kubeadmcfg.yaml
    kubeadm init phase certs etcd-healthcheck-client --config=/tmp/${HOST}/kubeadmcfg.yaml
    kubeadm init phase certs apiserver-etcd-client --config=/tmp/${HOST}/kubeadmcfg.yaml
    cp -R /etc/kubernetes/pki /tmp/${HOST}/

    # cleanup non-reusable certificate adn 
    # clean up certs that should not be copied off this host
    if (( $i > 0 ))
    then
        find /etc/kubernetes/pki -not -name ca.crt -not -name ca.key -type f -delete
        find /tmp/${HOST} -name ca.key -type f -delete
    fi 

done 

# ONLY FOR etcd0
kubeadm init phase etcd local --config=/root/kubeadmcfg.yaml

systemctl daemon-reload
systemctl enable --now kubelet
```

### the kubelet didn't come up

```
F0924 11:06:47.970963    5738 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
```

tried doing this
```
# kubeadm init phase kubeconfig kubelet --config=/root/kubeadmcfg.yaml
error execution phase kubeconfig/kubelet: couldn't create a kubeconfig; the CA files couldn't be loaded: failed to load certificate: couldn't load the certificate file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory
```

I do not see, why the ca.crt needed to be there, as I understood, the kubelet runs with a static manifest for etcd. this was generated with `kubeadm init phase etcd local`. Right? 

but tried this
```
[root@etcd1 tstark]# kubeadm init phase kubeconfig kubelet --config=/root/kubeadmcfg.yaml
error execution phase kubeconfig/kubelet: couldn't create a kubeconfig; the CA files couldn't be loaded: failed to load certificate: couldn't load the certificate file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory
To see the stack trace of this error execute with --v=5 or higher
[root@etcd1 tstark]# kubeadm init phase etcd local --config=/root/kubeadmcfg.yaml
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[root@etcd1 tstark]# kubeadm init phase kubeconfig kubelet --config=/root/kubeadmcfg.yaml
error execution phase kubeconfig/kubelet: couldn't create a kubeconfig; the CA files couldn't be loaded: failed to load certificate: couldn't load the certificate file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory
To see the stack trace of this error execute with --v=5 or higher
[root@etcd1 tstark]# kubeadm init phase kubelet-finalize all --config=/root/kubeadmcfg.yaml
[root@expr-etcd1 tstark]# kubeadm init phase kubelet-start --config=/root/kubeadmcfg.yaml
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
```

kubelet failed, with `server.go:253] unable to load client CA file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory`

next run, provide the requested ca.crt file
``
kubeadm init phase etcd local --config=/root/kubeadmcfg.yaml
kubeadm init phase kubeconfig kubelet --config=/root/kubeadmcfg.yaml
kubeadm init phase kubelet-finalize all --config=/root/kubeadmcfg.yaml
kubeadm init phase kubelet-start --config=/root/kubeadmcfg.yaml
# kubeadm init phase certs ca --config=/root/kubeletcfg.yaml
[certs] Generating "ca" certificate and key
[root@expr-etcd1 tstark]# kubeadm init phase kubelet-finalize all --config=/root/kubeadmcfg.yaml
[root@expr-etcd1 tstark]# kubeadm init phase kubelet-start --config=/root/kubeadmcfg.yaml
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
```

**Comment by neolit123** [comment]
Like i've mentioned above the kubelet startup does need the ca.crt file and you can generate it with kubeadm. It is required for validating the kube-api-server identity. This is an unrelated problem to the different container runtime.
