### ISSUE TITLE
Kubeadm init fails in v1.19.3

### ISSUE THREAD

**Issue by xsim** [kubernetes/kubeadm#2326]
## What keywords did you search in kubeadm issues before filing this one?

http://localhost:10248/healthz, ContainerManager failed, init, health

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):

kubeadm version: &version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:47:53Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
**Environment**:
- **Kubernetes version** (use `kubectl version`):Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
- **Cloud provider or hardware configuration**: Azure Virtual Machine
- **OS** (e.g. from /etc/os-release): Oracle Linux Server 7.9
- **Kernel** (e.g. `uname -a`): 4.14.35-1902.302.2.el7uek.x86_64

## What happened?

When using cri-0 1.19 and kubeadm 1.19 to init the cluster on a fresh oracle linux, it fails with:

`[kubelet-check] It seems like the kubelet isn't running or healthy. [kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp 127.0.0.1:10248: connect: connection refused.`

Using the same installation setup, I have also tried:
- cri-o 1.18 and kubeadm 1.18 -> kubeadm init is ok
- cri-o 1.19 and kubeadm 1.18 -> kubeadm init is ok
- cri-o 1.18 and kubeadm 1.19 -> kubeadm init is not ok, same issue as described above

## What you expected to happen?

Kubeadm init to succeed

## How to reproduce it (as minimally and precisely as possible)?
- Setup an oracle linux 7.9 environment with latest update
- Install cri-o v1.19.0
- Install kubeadm, kubectl and kubelet v.1.19.3
- Run kubeadm init 

## Anything else we need to know?

kubelet logs:

```
Oct 16 13:48:22 kube-oel-master kubelet[71204]: I1016 13:48:22.606588   71204 server.go:411] Version: v1.19.3
Oct 16 13:48:22 kube-oel-master kubelet[71204]: I1016 13:48:22.606766   71204 server.go:831] Client rotation is on, will bootstrap in background
Oct 16 13:48:22 kube-oel-master kubelet[71204]: I1016 13:48:22.608440   71204 certificate_store.go:130] Loading cert/key pair from "/var/lib/kubelet/pki/kubelet-client-current.pem".
Oct 16 13:48:22 kube-oel-master kubelet[71204]: I1016 13:48:22.609134   71204 dynamic_cafile_content.go:167] Starting client-ca-bundle::/etc/kubernetes/pki/ca.crt
Oct 16 13:48:22 kube-oel-master kubelet[71204]: W1016 13:48:22.609147   71204 container_manager_linux.go:951] CPUAccounting not enabled for pid: 71204
Oct 16 13:48:22 kube-oel-master kubelet[71204]: W1016 13:48:22.609155   71204 container_manager_linux.go:954] MemoryAccounting not enabled for pid: 71204
Oct 16 13:48:27 kube-oel-master kubelet[71204]: W1016 13:48:27.613126   71204 nvidia.go:61] NVIDIA GPU metrics will not be available: no NVIDIA devices found
Oct 16 13:48:27 kube-oel-master kubelet[71204]: I1016 13:48:27.616014   71204 server.go:640] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
Oct 16 13:48:27 kube-oel-master kubelet[71204]: I1016 13:48:27.616342   71204 container_manager_linux.go:276] container manager verified user specified cgroup-root exists: []
Oct 16 13:48:27 kube-oel-master kubelet[71204]: I1016 13:48:27.616364   71204 container_manager_linux.go:281] Creating Container Manager object based on Node Config: {RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: ContainerRuntime:remote CgroupsPerQOS:true CgroupRoot:/ CgroupDriver:systemd KubeletRootDir:/var/lib/kubelet ProtectKernelDefaults:false NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: ReservedSystemCPUs: EnforceNodeAllocatable:map[pods:{}] KubeReserved:map[] SystemReserved:map[] HardEvictionThresholds:[{Signal:memory.available Operator:LessThan Value:{Quantity:100Mi Percentage:0} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.1} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.inodesFree Operator:LessThan Value:{Quantity:<nil> Percentage:0.05} GracePeriod:0s MinReclaim:<nil>} {Signal:imagefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.15} GracePeriod:0s MinReclaim:<nil>}]} QOSReserved:map[] ExperimentalCPUManagerPolicy:none ExperimentalCPUManagerReconcilePeriod:10s ExperimentalPodPidsLimit:-1 EnforceCPULimits:true CPUCFSQuotaPeriod:100ms ExperimentalTopologyManagerPolicy:none}
Oct 16 13:48:27 kube-oel-master kubelet[71204]: I1016 13:48:27.616451   71204 topology_manager.go:126] [topologymanager] Creating topology manager with none policy
Oct 16 13:48:27 kube-oel-master kubelet[71204]: I1016 13:48:27.616460   71204 container_manager_linux.go:311] [topologymanager] Initializing Topology Manager with none policy
Oct 16 13:48:27 kube-oel-master kubelet[71204]: I1016 13:48:27.616465   71204 container_manager_linux.go:316] Creating device plugin manager: true
Oct 16 13:48:27 kube-oel-master kubelet[71204]: I1016 13:48:27.616584   71204 remote_runtime.go:59] parsed scheme: ""
Oct 16 13:48:27 kube-oel-master kubelet[71204]: I1016 13:48:27.616609   71204 remote_runtime.go:59] scheme "" not registered, fallback to default scheme
Oct 16 13:48:27 kube-oel-master kubelet[71204]: I1016 13:48:27.616651   71204 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/var/run/crio/crio.sock  <nil> 0 <nil>}] <nil> <nil>}
Oct 16 13:48:27 kube-oel-master kubelet[71204]: I1016 13:48:27.616658   71204 clientconn.go:948] ClientConn switching balancer to "pick_first"
Oct 16 13:48:27 kube-oel-master kubelet[71204]: I1016 13:48:27.616712   71204 remote_image.go:50] parsed scheme: ""
Oct 16 13:48:27 kube-oel-master kubelet[71204]: I1016 13:48:27.616718   71204 remote_image.go:50] scheme "" not registered, fallback to default scheme
Oct 16 13:48:27 kube-oel-master kubelet[71204]: I1016 13:48:27.616725   71204 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/var/run/crio/crio.sock  <nil> 0 <nil>}] <nil> <nil>}
Oct 16 13:48:27 kube-oel-master kubelet[71204]: I1016 13:48:27.616730   71204 clientconn.go:948] ClientConn switching balancer to "pick_first"
Oct 16 13:48:27 kube-oel-master kubelet[71204]: I1016 13:48:27.616757   71204 kubelet.go:261] Adding pod path: /etc/kubernetes/manifests
Oct 16 13:48:27 kube-oel-master kubelet[71204]: I1016 13:48:27.616793   71204 kubelet.go:273] Watching apiserver
Oct 16 13:48:27 kube-oel-master kubelet[71204]: E1016 13:48:27.620159   71204 reflector.go:127] k8s.io/kubernetes/pkg/kubelet/kubelet.go:438: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://10.0.0.10:6443/api/v1/nodes?fieldSelector=metadata.name%3Dkube-oel-master&limit=500&resourceVersion=0": dial tcp 10.0.0.10:6443: connect: connection refused
Oct 16 13:48:27 kube-oel-master kubelet[71204]: E1016 13:48:27.620221   71204 reflector.go:127] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://10.0.0.10:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp 10.0.0.10:6443: connect: connection refused
Oct 16 13:48:27 kube-oel-master kubelet[71204]: E1016 13:48:27.620321   71204 reflector.go:127] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to watch *v1.Pod: failed to list *v1.Pod: Get "https://10.0.0.10:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dkube-oel-master&limit=500&resourceVersion=0": dial tcp 10.0.0.10:6443: connect: connection refused
Oct 16 13:48:27 kube-oel-master kubelet[71204]: E1016 13:48:27.759360   71204 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
Oct 16 13:48:27 kube-oel-master kubelet[71204]: For verbose messaging see aws.Config.CredentialsChainVerboseErrors
Oct 16 13:48:27 kube-oel-master kubelet[71204]: I1016 13:48:27.765851   71204 kuberuntime_manager.go:214] Container runtime cri-o initialized, version: 1.19.0, apiVersion: v1alpha1
Oct 16 13:48:27 kube-oel-master kubelet[71204]: I1016 13:48:27.766320   71204 server.go:1147] Started kubelet
Oct 16 13:48:27 kube-oel-master kubelet[71204]: E1016 13:48:27.767128   71204 kubelet.go:1218] Image garbage collection failed once. Stats initialization may not have completed yet: failed to get imageFs info: unable to find data in memory cache
Oct 16 13:48:27 kube-oel-master kubelet[71204]: I1016 13:48:27.768127   71204 fs_resource_analyzer.go:64] Starting FS ResourceAnalyzer
Oct 16 13:48:27 kube-oel-master kubelet[71204]: E1016 13:48:27.768655   71204 event.go:273] Unable to write event: 'Post "https://10.0.0.10:6443/api/v1/namespaces/default/events": dial tcp 10.0.0.10:6443: connect: connection refused' (may retry after sleeping)
Oct 16 13:48:27 kube-oel-master kubelet[71204]: I1016 13:48:27.768908   71204 server.go:152] Starting to listen on 0.0.0.0:10250
Oct 16 13:48:27 kube-oel-master kubelet[71204]: I1016 13:48:27.769595   71204 server.go:424] Adding debug handlers to kubelet server.
Oct 16 13:48:27 kube-oel-master kubelet[71204]: I1016 13:48:27.770428   71204 volume_manager.go:265] Starting Kubelet Volume Manager
Oct 16 13:48:27 kube-oel-master kubelet[71204]: I1016 13:48:27.771072   71204 desired_state_of_world_populator.go:139] Desired state populator starts to run
Oct 16 13:48:27 kube-oel-master kubelet[71204]: E1016 13:48:27.771175   71204 controller.go:136] failed to ensure node lease exists, will retry in 200ms, error: Get "https://10.0.0.10:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/kube-oel-master?timeout=10s": dial tcp 10.0.0.10:6443: connect: connection refused
Oct 16 13:48:27 kube-oel-master kubelet[71204]: E1016 13:48:27.771266   71204 reflector.go:127] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: Get "https://10.0.0.10:6443/apis/storage.k8s.io/v1/csidrivers?limit=500&resourceVersion=0": dial tcp 10.0.0.10:6443: connect: connection refused
Oct 16 13:48:27 kube-oel-master kubelet[71204]: I1016 13:48:27.798169   71204 cpu_manager.go:184] [cpumanager] starting with none policy
Oct 16 13:48:27 kube-oel-master kubelet[71204]: I1016 13:48:27.798185   71204 cpu_manager.go:185] [cpumanager] reconciling every 10s
Oct 16 13:48:27 kube-oel-master kubelet[71204]: I1016 13:48:27.798199   71204 state_mem.go:36] [cpumanager] initializing new in-memory state store
Oct 16 13:48:27 kube-oel-master kubelet[71204]: I1016 13:48:27.798333   71204 state_mem.go:88] [cpumanager] updated default cpuset: ""
Oct 16 13:48:27 kube-oel-master kubelet[71204]: I1016 13:48:27.798341   71204 state_mem.go:96] [cpumanager] updated cpuset assignments: "map[]"
Oct 16 13:48:27 kube-oel-master kubelet[71204]: I1016 13:48:27.798351   71204 policy_none.go:43] [cpumanager] none policy: Start
Oct 16 13:48:27 kube-oel-master kubelet[71204]: F1016 13:48:27.798366   71204 kubelet.go:1296] Failed to start ContainerManager failed to get rootfs info: failed to get device for dir "/var/lib/kubelet": could not find device with major: 0, minor: 41 in cached partitions map
Oct 16 13:48:27 kube-oel-master kubelet[71204]: goroutine 212 [running]:
```

**Comment by neolit123** [comment]
hi, this seems like a problem with the node / kubelet and not kubeadm.

there are similar tickets logged in the kubernetes/kubernetes repository:
https://github.com/kubernetes/kubernetes/search?q=%22ContainerManager+failed+to+get+rootfs+info%3A+failed+to+get+device+for+dir%22&type=issues

/close
/kind support
/sig node
