### ISSUE TITLE
failing kinder jobs at latest that call kubeadm reset

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubeadm#2943]
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-external-ca-latest
Started to fail yesterday. @chendave @SataQiu @neolit123 

```

I1016 15:45:24.588701   94159 etcd.go:214] retrieving etcd endpoints from "kubeadm.kubernetes.io/etcd.advertise-client-urls" annotation in etcd Pods
E1016 15:45:24.589382   94159 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1bbd500?, 0x3116220})
	vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x1e29dc0?})
	vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x6b
panic({0x1bbd500?, 0x3116220?})
	/usr/local/go/src/runtime/panic.go:914 +0x21f
k8s.io/client-go/kubernetes.(*Clientset).CoreV1(0xc000692d00?)
	vendor/k8s.io/client-go/kubernetes/clientset.go:306
k8s.io/kubernetes/cmd/kubeadm/app/util/etcd.getRawEtcdEndpointsFromPodAnnotationWithoutRetry({0x21a2050, 0x0})
	cmd/kubeadm/app/util/etcd/etcd.go:215 +0xde
k8s.io/kubernetes/cmd/kubeadm/app/util/etcd.getRawEtcdEndpointsFromPodAnnotation.func1()
	cmd/kubeadm/app/util/etcd/etcd.go:190 +0x3c
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection(0x36?)
	vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:145 +0x3e
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff({0x3b9aca00, 0x3ff0000000000000, 0x3fb999999999999a, 0x1e, 0x0}, 0xc0000c47e0?)
	vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:461 +0x5a
k8s.io/kubernetes/cmd/kubeadm/app/util/etcd.getRawEtcdEndpointsFromPodAnnotation({0x21a2050?, 0x0?}, {0x3b9aca00, 0x3ff0000000000000, 0x3fb999999999999a, 0x1e, 0x0})
	cmd/kubeadm/app/util/etcd/etcd.go:188 +0xd9
k8s.io/kubernetes/cmd/kubeadm/app/util/etcd.getEtcdEndpointsWithBackoff(...)
	cmd/kubeadm/app/util/etcd/etcd.go:179
k8s.io/kubernetes/cmd/kubeadm/app/util/etcd.getEtcdEndpoints({0x21a2050?, 0x0?})
	cmd/kubeadm/app/util/etcd/etcd.go:175 +0x5c
k8s.io/kubernetes/cmd/kubeadm/app/util/etcd.NewFromCluster({0x21a2050?, 0x0?}, {0x0, 0x0})
	cmd/kubeadm/app/util/etcd/etcd.go:146 +0x45
k8s.io/kubernetes/cmd/kubeadm/app/phases/etcd.RemoveStackedEtcdMemberFromCluster({0x21a2050, 0x0}, 0xc0004b0e00)
	cmd/kubeadm/app/phases/etcd/local.go:94 +0xd9
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/reset.runRemoveETCDMemberPhase({0x1d40aa0?, 0xc00038f000?})
	cmd/kubeadm/app/cmd/phases/reset/removeetcdmember.go:66 +0x28a
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1(0xc0003518c0)
	cmd/kubeadm/app/cmd/phases/workflow/runner.go:259 +0x11a
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll(...)
	cmd/kubeadm/app/cmd/phases/workflow/runner.go:446
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run(0xc00068e3f0, {0xc000390780, 0x0, 0x2})
	cmd/kubeadm/app/cmd/phases/workflow/runner.go:232 +0x3b9
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdReset.func1(0xc00034c800?, {0xc000390780, 0x0, 0x2})
	cmd/kubeadm/app/cmd/reset.go:214 +0x65
github.com/spf13/cobra.(*Command).execute(0xc00034e300, {0xc000390760, 0x2, 0x2})
	vendor/github.com/spf13/cobra/command.go:940 +0x87c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001dfb00)
	vendor/github.com/spf13/cobra/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(0x21672e0?)
	vendor/github.com/spf13/cobra/command.go:992 +0x13
k8s.io/kubernetes/cmd/kubeadm/app.Run()
	cmd/kubeadm/app/kubeadm.go:50 +0x155
main.main()
	cmd/kubeadm/kubeadm.go:25 +0x13
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc0 pc=0x14eade0]
```

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/blob/86676bce04dac096f89bea4d0fcbc6452630c5d2/cmd/kubeadm/app/cmd/reset.go#L119-L128

```
I1016 15:45:24.588634   94159 reset.go:127] [reset] Could not obtain a client set from the kubeconfig file: /etc/kubernetes/admin.conf
I1016 15:45:24.588642   94159 reset.go:145] [reset] Using specified CRI socket: unix:///var/run/containerd/containerd.sock
I1016 15:45:24.588663   94159 removeetcdmember.go:60] [reset] Checking for etcd config
W1016 15:45:24.588669   94159 removeetcdmember.go:106] [reset] No kubeadm config, using etcd pod spec to get data directory
I1016 15:45:24.588694   94159 local.go:93] [etcd] creating etcd client that connects to etcd pods
```

**Comment by neolit123** [comment]
all our jobs at latest that do reset are failing:
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm

we merged a few PRs yesterday:
https://github.com/kubernetes/kubernetes/pulls?q=label%3Aarea%2Fkubeadm+is%3Aclosed+is%3Apr+sort%3Aupdated-desc

maybe something from?
https://github.com/kubernetes/kubernetes/pull/119946/
@chendave 

the rest of the PRs don't seem related.

**Comment by pacoxu** [comment]
It also fail in https://testgrid.k8s.io/sig-release-master-informing#kubeadm-kinder-latest.

CI is green after the revert.
