### ISSUE TITLE
[failing-test] kubeadm-kinder-no-addons-latest

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2998]
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-no-addons-latest

```
I0116 07:48:14.567735     296 round_trippers.go:553] GET https://172.17.0.2:6443/api/v1/namespaces/kube-system/configmaps/kube-proxy?timeout=10s 404 Not Found in 3 milliseconds
I0116 07:48:15.067484     296 round_trippers.go:553] GET https://172.17.0.2:6443/api/v1/namespaces/kube-system/configmaps/kube-proxy?timeout=10s 404 Not Found in 3 milliseconds
I0116 07:48:15.567380     296 round_trippers.go:553] GET https://172.17.0.2:6443/api/v1/namespaces/kube-system/configmaps/kube-proxy?timeout=10s 404 Not Found in 2 milliseconds
I0116 07:48:16.068157     296 round_trippers.go:553] GET https://172.17.0.2:6443/api/v1/namespaces/kube-system/configmaps/kube-proxy?timeout=10s 404 Not Found in 2 milliseconds
I0116 07:48:16.567953     296 round_trippers.go:553] GET https://172.17.0.2:6443/api/v1/namespaces/kube-system/configmaps/kube-proxy?timeout=10s 404 Not Found in 3 milliseconds
I0116 07:48:17.067409     296 round_trippers.go:553] GET https://172.17.0.2:6443/api/v1/namespaces/kube-system/configmaps/kube-proxy?timeout=10s 404 Not Found in 2 milliseconds
I0116 07:48:17.566818     296 round_trippers.go:553] GET https://172.17.0.2:6443/api/v1/namespaces/kube-system/configmaps/kube-proxy?timeout=10s 404 Not Found in 2 milliseconds
I0116 07:48:18.067240     296 round_trippers.go:553] GET https://172.17.0.2:6443/api/v1/namespaces/kube-system/configmaps/kube-proxy?timeout=10s 404 Not Found in 2 milliseconds
I0116 07:48:18.567621     296 round_trippers.go:553] GET https://172.17.0.2:6443/api/v1/namespaces/kube-system/configmaps/kube-proxy?timeout=10s 404 Not Found in 2 milliseconds
I0116 07:48:19.067083     296 round_trippers.go:553] GET https://172.17.0.2:6443/api/v1/namespaces/kube-system/configmaps/kube-proxy?timeout=10s 404 Not Found in 2 milliseconds
I0116 07:48:19.567266     296 round_trippers.go:553] GET https://172.17.0.2:6443/api/v1/namespaces/kube-system/configmaps/kube-proxy?timeout=10s 404 Not Found in 2 milliseconds
I0116 07:48:20.067939     296 round_trippers.go:553] GET https://172.17.0.2:6443/api/v1/namespaces/kube-system/configmaps/kube-proxy?timeout=10s 404 Not Found in 3 milliseconds
client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline
could not download the kube-proxy configuration from ConfigMap "kube-proxy"
k8s.io/kubernetes/cmd/kubeadm/app/componentconfigs.kubeProxyConfigFromCluster
	k8s.io/kubernetes/cmd/kubeadm/app/componentconfigs/kubeproxy.go:58
k8s.io/kubernetes/cmd/kubeadm/app/componentconfigs.(*handler).FromCluster
	k8s.io/kubernetes/cmd/kubeadm/app/componentconfigs/configset.go:116
k8s.io/kubernetes/cmd/kubeadm/app/componentconfigs.FetchFromCluster
	k8s.io/kubernetes/cmd/kubeadm/app/componentconfigs/configset.go:216
k8s.io/kubernetes/cmd/kubeadm/app/util/config.getInitConfigurationFromCluster
	k8s.io/kubernetes/cmd/kubeadm/app/util/config/cluster.go:104
k8s.io/kubernetes/cmd/kubeadm/app/util/config.FetchInitConfigurationFromCluster
	k8s.io/kubernetes/cmd/kubeadm/app/util/config/cluster.go:57
k8s.io/kubernetes/cmd/kubeadm/app/cmd.fetchInitConfiguration
	k8s.io/kubernetes/cmd/kubeadm/app/cmd/join.go:623
k8s.io/kubernetes/cmd/kubeadm/app/cmd.fetchInitConfigurationFromJoinConfiguration
	k8s.io/kubernetes/cmd/kubeadm/app/cmd/join.go:593
k8s.io/kubernetes/cmd/kubeadm/app/cmd.(*joinData).InitCfg
	k8s.io/kubernetes/cmd/kubeadm/app/cmd/join.go:547
```

i suppose it's this change, but it seems like very short retries, they are supposed to be at 50ms interval instead:
https://github.com/kubernetes/kubernetes/pull/122811/files#diff-7ff28f066de82deb50838fed82f22b4ff7d33a1ccb406be89f1ca318572ff077R75

https://github.com/kubernetes/kubernetes/blob/f40ff3d9ffb2a06ebb256b6e4c5d1b62079bb3b9/cmd/kubeadm/app/componentconfigs/kubeproxy.go#L53-L62

**Comment by neolit123** [comment]
a green run from a few days ago has this:
```
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'
I0115 19:44:58.001693     307 round_trippers.go:553] GET https://172.17.0.2:6443/api/v1/namespaces/kube-system/configmaps/kubeadm-config?timeout=10s 200 OK in 6 milliseconds
I0115 19:44:58.002749     307 kubeproxy.go:55] attempting to download the KubeProxyConfiguration from ConfigMap "kube-proxy"
I0115 19:44:58.004796     307 round_trippers.go:553] GET https://172.17.0.2:6443/api/v1/namespaces/kube-system/configmaps/kube-proxy?timeout=10s 404 Not Found in 1 milliseconds
I0115 19:44:58.018642     307 round_trippers.go:553] GET https://172.17.0.2:6443/api/v1/namespaces/kube-system/configmaps/kube-proxy?timeout=10s 404 Not Found in 2 milliseconds
I0115 19:44:58.074765     307 round_trippers.go:553] GET https://172.17.0.2:6443/api/v1/namespaces/kube-system/configmaps/kube-proxy?timeout=10s 404 Not Found in 2 milliseconds
I0115 19:44:58.339779     307 round_trippers.go:553] GET https://172.17.0.2:6443/api/v1/namespaces/kube-system/configmaps/kube-proxy?timeout=10s 404 Not Found in 2 milliseconds
W0115 19:44:58.339962     307 configset.go:78] Warning: No kubeproxy.config.k8s.io/v1alpha1 config is loaded. Continuing without it: configmaps "kube-proxy" not found
I0115 19:44:58.339984     307 kubelet.go:74] attempting to download the KubeletConfiguration from ConfigMap "kubelet-config"
I0115 19:44:58.342179     307 round_trippers.go:553] GET https://172.17.0.2:6443/api/v1/namespaces/kube-system/configmaps/kubelet-config?timeout=10s 200 OK in 2 milliseconds
I0115 19:44:58.344585     307 initconfiguration.go:114] skip CRI socket detection, fill with the default CRI socket unix:///var/run/containerd/containerd.sock
```

so looks like in the red run logs here:
https://github.com/kubernetes/kubeadm/issues/2998#issue-2086906039
we are not returning the right error and showing the warning:
https://github.com/kubernetes/kubernetes/pull/122811/files#diff-7ff28f066de82deb50838fed82f22b4ff7d33a1ccb406be89f1ca318572ff077R78

**Comment by neolit123** [comment]
so it seems like when i switched from exp backoff to PollUntilContextTImeout the returned error became different:

exp-backoff:
> configmaps "kube-proxy" not found
 
polluntilcontexttimeout:
> client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline

i'm not sure, but i think the point of the second error is that the timeout of 350ms is too short.

**Comment by neolit123** [comment]
i was able to reproduce the bug in the e2e test, but not in a unit test with `fake.NewSimpleClientset()`.
looks like this is just some strange effect of using a context in the poll.

this seems to fix it:
```diff
diff --git a/cmd/kubeadm/app/util/apiclient/idempotency.go b/cmd/kubeadm/app/util/apiclient/idempotency.go
index 828dab9c7d7..a5fda38f4d4 100644
--- a/cmd/kubeadm/app/util/apiclient/idempotency.go
+++ b/cmd/kubeadm/app/util/apiclient/idempotency.go
@@ -339,7 +339,9 @@ func GetConfigMapWithShortRetry(client clientset.Interface, namespace, name stri
        var cm *v1.ConfigMap
        var lastError error
        err := wait.PollUntilContextTimeout(context.Background(),
-               time.Millisecond*50, time.Millisecond*340,
+               // For short intervals and timeouts, avoid having: x = timeout % interval,
+               // where x < interval / 2.
+               time.Millisecond*50, time.Millisecond*340,
                true, func(ctx context.Context) (bool, error) {
                        var err error
                        cm, err = client.CoreV1().ConfigMaps(namespace).Get(ctx, name, metav1.GetOptions{})

```

but i wonder if it would flake.

before sending a PR, @SataQiu @pacoxu any better ideas to avoid the `client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline` error?

**Comment by neolit123** [comment]
latest attempt to fix
https://github.com/kubernetes/kubernetes/pull/122841

**Comment by neolit123** [comment]
reopening because there is yet another error at "latest" jobs:
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-latest
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-latest/1748061359985135616/build-log.txt

```
I0118 21:52:50.030404    1997 round_trippers.go:553] GET https://172.17.0.7:6443/api/v1/namespaces/kube-system/configmaps/kubeadm-config?timeout=10s  in 350 milliseconds
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x110 pc=0x17cd87c]

goroutine 1 [running]:
k8s.io/kubernetes/cmd/kubeadm/app/util/config.getInitConfigurationFromCluster({0x1f1e835, 0xf}, {0x223e390, 0xc00048dd40}, 0x0, 0x0)
	k8s.io/kubernetes/cmd/kubeadm/app/util/config/cluster.go:88 +0xfc
k8s.io/kubernetes/cmd/kubeadm/app/util/config.FetchInitConfigurationFromCluster({0x223e390, 0xc00048dd40}, {0x0?, 0x0?}, {0x1f10c6e, 0x5}, 0x0?, 0x0?)
	k8s.io/kubernetes/cmd/kubeadm/app/util/config/cluster.go:57 +0x1c8
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newResetData(0x1c1ef00?, 0xc0005ca0f0, {0x2201e60?, 0xc000126018}, {0x2201e80?, 0xc000126020}, 0x0?)
	k8s.io/kubernetes/cmd/kubeadm/app/cmd/reset.go:122 +0x2be
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdReset.func2(0x0?, {0x0?, 0x0?, 0x0?})
	k8s.io/kubernetes/cmd/kubeadm/app/cmd/reset.go:240 +0xc5
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).InitData(0xc00020c3f0, {0xc000148f20?, 0x0?, 0x0?})
	k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:183 +0x38
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdReset.func1(0xc000696200?, {0xc000148f20, 0x0, 0x2})
	k8s.io/kubernetes/cmd/kubeadm/app/cmd/reset.go:207 +0x2f
github.com/spf13/cobra.(*Command).execute(0xc000694300, {0xc000148f00, 0x2, 0x2})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x87c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000004600)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(0x2201e60?)
	github.com/spf13/cobra@v1.7.0/command.go:992 +0x13
k8s.io/kubernetes/cmd/kubeadm/app.Run()
	k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:52 +0x18a
main.main()
	k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25 +0x13
Error: failed to exec action kubeadm-reset: exit status 2
 exit status 1

# task-10-delete
```

not able to unit test or reproduce it locally. the problem is the API call takes 350ms.

https://github.com/kubernetes/kubernetes/pull/122841
my previous PR was OK, but it missed handling yet another scenario.
- API call ends up too slow, more than the parent context timeout
- context deadline error is returned, but it is handled as nil
- lastError ends up as a overall nil
- the function GetConfigMapWithShortRetry returns `nil, nil`, which then panics.

it is possible at the end of GetConfigMapWithShortRetry to have another `if lastError == nil { lastError = nil }`, but this is getting too messy and there is another problem. we actually want the API call to block for a while until it fetches a good config map. that was what the exponential backoff was doing. if we pass the parent context to the API call this short timeout function will always error on slow setups even if the config map is present in the cluster. we actually want the API call to run for a while and if  the next iteration reaches timeout, just return the context timeout error from the poll.

new PR (hopefully final for these bugs....)
https://github.com/kubernetes/kubernetes/pull/122850
