### ISSUE TITLE
kubeadm token create fails

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#436]
## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.2.3561+523ec9c78a4ad3-dirty", GitCommit:"523ec9c78a4ad34afe72dfc2a41782d998511fe0", GitTreeState:"dirty", BuildDate:"2017-09-12T21:16:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}

## What happened?
when you run `kubeadm create token` you get

```
[kubeadm] WARNING: starting in 1.8, tokens expire after 24 hours by default (if you require a non-expiring token use --ttl 0)
panic: assignment to entry in nil map

goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/sets.String.Insert(0x0, 0x5ccea40, 0x2, 0x2)
	/Users/fabrizio/Documents/Workspace/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/sets/string.go:51 +0x71
k8s.io/kubernetes/cmd/kubeadm/app/cmd.RunCreateToken(0x5a466c0, 0xc420080008, 0x5a79a20, 0xc420a7cc30, 0xc420ab9a00, 0x17, 0x4e94914f0000, 0x5ccea40, 0x2, 0x2, ...)
	/Users/fabrizio/Documents/Workspace/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/token.go:217 +0xa5
k8s.io/kubernetes/cmd/kubeadm/app/cmd.NewCmdToken.func1(0xc4202d2480, 0x5d09f08, 0x0, 0x0)
	/Users/fabrizio/Documents/Workspace/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/token.go:119 +0x21e
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc4202d2480, 0x5d09f08, 0x0, 0x0, 0xc4202d2480, 0x5d09f08)
	/Users/fabrizio/Documents/Workspace/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:603 +0x22b
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4202006c0, 0xc4202be6c0, 0xc4202078c0, 0xc420201440)
	/Users/fabrizio/Documents/Workspace/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:689 +0x339
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4202006c0, 0xc420080000, 0x5a466c0)
	/Users/fabrizio/Documents/Workspace/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:648 +0x2b
k8s.io/kubernetes/cmd/kubeadm/app.Run(0xc4200001a0, 0xc4200001a0)
	/Users/fabrizio/Documents/Workspace/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:34 +0xbe
main.main()
	/Users/fabrizio/Documents/Workspace/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:26 +0x22
````

**Comment by luxas** [comment]
Now fixed, thanks!
