### ISSUE TITLE
controller-manager panics when configured to use gce cloud-provider

### ISSUE THREAD

**Issue by shashidharatd** [kubernetes/kubeadm#555]
## Is this a BUG REPORT or FEATURE REQUEST?
/kind bug

## Versions

**kubeadm version** (use `kubeadm version`): stable

**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.10.0-alpha.0
- **Cloud provider or hardware configuration**: gce

## What happened?
When configured with gce cloud-provider kube-controller-manager panics while creating a loadbalancer service

## What you expected to happen?
provisioning loadbalancer service should succeed

## How to reproduce it (as minimally and precisely as possible)?
Configure the k8s cluster to run with gce cloud-provider.
Create a loadbalancer type service.
See the controller-manager status and logs.

## Anything else we need to know?
**kubeadm config file**
```
kind: MasterConfiguration
apiVersion: kubeadm.k8s.io/v1alpha1
api:
  advertiseAddress: "35.184.211.234"
  bindPort: 443
networking:
  podSubnet: "10.32.0.0/12"
kubernetesVersion: "latest"
token: "c0059c.6c49609f23840048"
cloudProvider: "gce"
```
**call trace of panic**
```
{"log":"E1120 08:53:51.758928       1 runtime.go:66] Observed a panic: \"invalid memory address or nil pointer dereference\" (runtime error: invalid memory address or nil pointer dereference)\n","stream":"stderr","time":"2017-11-20T08:53:51.75906037Z"}
{"log":"/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72\n","stream":"stderr","time":"2017-11-20T08:53:51.759099606Z"}
{"log":"/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65\n","stream":"stderr","time":"2017-11-20T08:53:51.759103487Z"}
{"log":"/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51\n","stream":"stderr","time":"2017-11-20T08:53:51.759106461Z"}
{"log":"/usr/local/go/src/runtime/asm_amd64.s:509\n","stream":"stderr","time":"2017-11-20T08:53:51.759109986Z"}
{"log":"/usr/local/go/src/runtime/panic.go:491\n","stream":"stderr","time":"2017-11-20T08:53:51.759112398Z"}
{"log":"/usr/local/go/src/runtime/panic.go:63\n","stream":"stderr","time":"2017-11-20T08:53:51.7591148Z"}
{"log":"/usr/local/go/src/runtime/signal_unix.go:367\n","stream":"stderr","time":"2017-11-20T08:53:51.759117177Z"}
{"log":"/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/gce_alpha.go:49\n","stream":"stderr","time":"2017-11-20T08:53:51.759119905Z"}
{"log":"/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/gce_loadbalancer_external.go:1009\n","stream":"stderr","time":"2017-11-20T08:53:51.759123149Z"}
{"log":"/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/gce_loadbalancer_external.go:74\n","stream":"stderr","time":"2017-11-20T08:53:51.759125763Z"}
{"log":"/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/gce_loadbalancer.go:151\n","stream":"stderr","time":"2017-11-20T08:53:51.759128293Z"}
{"log":"/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:374\n","stream":"stderr","time":"2017-11-20T08:53:51.75913078Z"}
{"log":"/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:306\n","stream":"stderr","time":"2017-11-20T08:53:51.759133192Z"}
{"log":"/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:249\n","stream":"stderr","time":"2017-11-20T08:53:51.759135515Z"}
{"log":"/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:771\n","stream":"stderr","time":"2017-11-20T08:53:51.759138058Z"}
{"log":"/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:213\n","stream":"stderr","time":"2017-11-20T08:53:51.759140579Z"}
{"log":"/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:217\n","stream":"stderr","time":"2017-11-20T08:53:51.759152175Z"}
{"log":"/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:195\n","stream":"stderr","time":"2017-11-20T08:53:51.759154766Z"}
{"log":"/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\n","stream":"stderr","time":"2017-11-20T08:53:51.759162885Z"}
{"log":"/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\n","stream":"stderr","time":"2017-11-20T08:53:51.759165598Z"}
{"log":"/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88\n","stream":"stderr","time":"2017-11-20T08:53:51.759168086Z"}
{"log":"/usr/local/go/src/runtime/asm_amd64.s:2337\n","stream":"stderr","time":"2017-11-20T08:53:51.759170494Z"}
{"log":"panic: runtime error: invalid memory address or nil pointer dereference [recovered]\n","stream":"stderr","time":"2017-11-20T08:53:51.761918876Z"}
{"log":"\u0009panic: runtime error: invalid memory address or nil pointer dereference\n","stream":"stderr","time":"2017-11-20T08:53:51.761988824Z"}
{"log":"[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x198230d]\n","stream":"stderr","time":"2017-11-20T08:53:51.76207264Z"}
{"log":"\n","stream":"stderr","time":"2017-11-20T08:53:51.762084946Z"}
{"log":"goroutine 1493 [running]:\n","stream":"stderr","time":"2017-11-20T08:53:51.762140945Z"}
{"log":"k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)\n","stream":"stderr","time":"2017-11-20T08:53:51.762344712Z"}
{"log":"\u0009/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x111\n","stream":"stderr","time":"2017-11-20T08:53:51.762402948Z"}
{"log":"panic(0x2cc34e0, 0x4e2b100)\n","stream":"stderr","time":"2017-11-20T08:53:51.762465287Z"}
{"log":"\u0009/usr/local/go/src/runtime/panic.go:491 +0x283\n","stream":"stderr","time":"2017-11-20T08:53:51.762535659Z"}
{"log":"k8s.io/kubernetes/pkg/cloudprovider/providers/gce.(*AlphaFeatureGate).Enabled(...)\n","stream":"stderr","time":"2017-11-20T08:53:51.762560914Z"}
{"log":"\u0009/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/gce_alpha.go:49\n","stream":"stderr","time":"2017-11-20T08:53:51.762613549Z"}
{"log":"k8s.io/kubernetes/pkg/cloudprovider/providers/gce.(*GCECloud).getServiceNetworkTier(0xc4206d6000, 0xc42010ebc0, 0x32, 0xc42249b660, 0x6, 0x6)\n","stream":"stderr","time":"2017-11-20T08:53:51.762743852Z"}
{"log":"\u0009/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/gce_loadbalancer_external.go:1009 +0x2d\n","stream":"stderr","time":"2017-11-20T08:53:51.762816154Z"}
{"log":"k8s.io/kubernetes/pkg/cloudprovider/providers/gce.(*GCECloud).ensureExternalLoadBalancer(0xc4206d6000, 0x3337b1c, 0xa, 0xc4209f6750, 0x10, 0xc42010ebc0, 0x0, 0xc42251c5b0, 0x2, 0x2, ...)\n","stream":"stderr","time":"2017-11-20T08:53:51.76301498Z"}
{"log":"\u0009/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/gce_loadbalancer_external.go:74 +0x8b5\n","stream":"stderr","time":"2017-11-20T08:53:51.763083001Z"}
{"log":"k8s.io/kubernetes/pkg/cloudprovider/providers/gce.(*GCECloud).EnsureLoadBalancer(0xc4206d6000, 0x3337b1c, 0xa, 0xc42010ebc0, 0xc42251c5b0, 0x2, 0x2, 0xbe7cc3e7de326fff, 0x351e30a6c, 0x4e470a0)\n","stream":"stderr","time":"2017-11-20T08:53:51.763288632Z"}
{"log":"\u0009/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/gce_loadbalancer.go:151 +0x752\n","stream":"stderr","time":"2017-11-20T08:53:51.763355785Z"}
{"log":"k8s.io/kubernetes/pkg/controller/service.(*ServiceController).ensureLoadBalancer(0xc4209709a0, 0xc42010ebc0, 0xc42010ebc0, 0x3330999, 0x6)\n","stream":"stderr","time":"2017-11-20T08:53:51.763477215Z"}
{"log":"\u0009/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:374 +0xcc\n","stream":"stderr","time":"2017-11-20T08:53:51.763544163Z"}
{"log":"k8s.io/kubernetes/pkg/controller/service.(*ServiceController).createLoadBalancerIfNeeded(0xc4209709a0, 0xc42096b900, 0x3c, 0xc42010ebc0, 0xc42249bc40, 0xc42249bc78, 0x1a0d442)\n","stream":"stderr","time":"2017-11-20T08:53:51.763690716Z"}
{"log":"\u0009/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:306 +0x20e\n","stream":"stderr","time":"2017-11-20T08:53:51.763758126Z"}
{"log":"k8s.io/kubernetes/pkg/controller/service.(*ServiceController).processServiceUpdate(0xc4209709a0, 0xc42251c570, 0xc42010ebc0, 0xc42096b900, 0x3c, 0x0, 0x0, 0x0)\n","stream":"stderr","time":"2017-11-20T08:53:51.763918651Z"}
{"log":"\u0009/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:249 +0xeb\n","stream":"stderr","time":"2017-11-20T08:53:51.763985043Z"}
{"log":"k8s.io/kubernetes/pkg/controller/service.(*ServiceController).syncService(0xc4209709a0, 0xc42096b900, 0x3c, 0x0, 0x0)\n","stream":"stderr","time":"2017-11-20T08:53:51.764168087Z"}
{"log":"\u0009/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:771 +0x3aa\n","stream":"stderr","time":"2017-11-20T08:53:51.764237303Z"}
{"log":"k8s.io/kubernetes/pkg/controller/service.(*ServiceController).worker.func1(0xc4209709a0)\n","stream":"stderr","time":"2017-11-20T08:53:51.76427336Z"}
{"log":"\u0009/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:213 +0xd9\n","stream":"stderr","time":"2017-11-20T08:53:51.764339877Z"}
{"log":"k8s.io/kubernetes/pkg/controller/service.(*ServiceController).worker(0xc4209709a0)\n","stream":"stderr","time":"2017-11-20T08:53:51.764385504Z"}
{"log":"\u0009/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:217 +0x2b\n","stream":"stderr","time":"2017-11-20T08:53:51.764452837Z"}
{"log":"k8s.io/kubernetes/pkg/controller/service.(*ServiceController).(k8s.io/kubernetes/pkg/controller/service.worker)-fm()\n","stream":"stderr","time":"2017-11-20T08:53:51.764481106Z"}
{"log":"\u0009/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:195 +0x2a\n","stream":"stderr","time":"2017-11-20T08:53:51.764552672Z"}
{"log":"k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc42247a870)\n","stream":"stderr","time":"2017-11-20T08:53:51.764598387Z"}
{"log":"\u0009/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x5e\n","stream":"stderr","time":"2017-11-20T08:53:51.76465534Z"}
{"log":"k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc42247a870, 0x3b9aca00, 0x0, 0x1, 0xc420050360)\n","stream":"stderr","time":"2017-11-20T08:53:51.764769648Z"}
{"log":"\u0009/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd\n","stream":"stderr","time":"2017-11-20T08:53:51.764837011Z"}
{"log":"k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc42247a870, 0x3b9aca00, 0xc420050360)\n","stream":"stderr","time":"2017-11-20T08:53:51.764913166Z"}
{"log":"\u0009/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d\n","stream":"stderr","time":"2017-11-20T08:53:51.764943927Z"}
{"log":"created by k8s.io/kubernetes/pkg/controller/service.(*ServiceController).Run\n","stream":"stderr","time":"2017-11-20T08:53:51.764947281Z"}
{"log":"\u0009/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:195 +0x20c\n","stream":"stderr","time":"2017-11-20T08:53:51.76494967Z"}
```

/cc @luxas @kubernetes/sig-cluster-lifecycle-bugs

**Comment by wackxu** [comment]
Perhaps https://github.com/kubernetes/kubernetes/pull/56021 is to resolve it.

**Comment by xiangpengzhao** [comment]
yeah I think this issue is the same with https://github.com/kubernetes/kubernetes/issues/56009 which would be fixed by https://github.com/kubernetes/kubernetes/pull/56021.

**Comment by luxas** [comment]
This seems to be fixed now, closing.
Thanks @xiangpengzhao!
