### ISSUE TITLE
panic in kubeadm init --dry-run with containerd

### ISSUE THREAD

**Issue by NeilW** [kubernetes/kubeadm#922]
BUG REPORT 

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0-beta.2", GitCommit:"be2cfcf9e44b5162a294e977329d6c8194748c4e", GitTreeState:"clean", BuildDate:"2018-06-07T16:19:15Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0-beta.2", GitCommit:"be2cfcf9e44b5162a294e977329d6c8194748c4e", GitTreeState:"clean", BuildDate:"2018-06-07T16:21:58Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
- **Cloud provider or hardware configuration**:
Brightbox
- **OS** (e.g. from /etc/os-release):
Ubuntu 18.04 LTS
- **Kernel** (e.g. `uname -a`):
Linux srv-nay4u 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- **Others**:
containerd github.com/containerd/containerd v1.1.0 209a7fc3e4a32ef71a8c7b50c68fc8398415badf

## What happened?

kubeadm caused a panic

```
[dryrun] Resource name: "srv-nay4u"
[dryrun] Attached patch:
	{"metadata":{"labels":{"node-role.kubernetes.io/master":""}},"spec":{"taints":[{"effect":"NoSchedule","key":"node-role.kubernetes.io/master"}]}}
[patchnode] Uploading the CRI Socket information "/var/run/containerd/containerd.sock" to the Node API object "srv-nay4u" as an annotation
[dryrun] Would perform action GET on resource "nodes" in API group "core/v1"
[dryrun] Resource name: "srv-nay4u"
panic: assignment to entry in nil map

goroutine 1 [running]:
k8s.io/kubernetes/cmd/kubeadm/app/phases/patchnode.annotateNodeWithCRISocket(...)
	/workspace/anago-v1.11.0-beta.1.299+be2cfcf9e44b51/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/patchnode/patchnode.go:39
k8s.io/kubernetes/cmd/kubeadm/app/phases/patchnode.AnnotateCRISocket.func1(0xc4207b1080)
	/workspace/anago-v1.11.0-beta.1.299+be2cfcf9e44b51/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/patchnode/patchnode.go:34 +0x69
k8s.io/kubernetes/cmd/kubeadm/app/util/apiclient.PatchNode.func1(0xc42040a5a0, 0xc42046b5af, 0xc420038301)
	/workspace/anago-v1.11.0-beta.1.299+be2cfcf9e44b51/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/util/apiclient/idempotency.go:218 +0x1b1
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.WaitFor(0xc4206ffba0, 0xc4207b4ab0, 0xc42040a540, 0x90385d, 0x1697d60)
	/workspace/anago-v1.11.0-beta.1.299+be2cfcf9e44b51/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:331 +0x6b
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.pollInternal(0xc4206ffba0, 0xc4207b4ab0, 0x0, 0x0)
	/workspace/anago-v1.11.0-beta.1.299+be2cfcf9e44b51/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:227 +0x8a
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Poll(0x1dcd6500, 0x1bf08eb000, 0xc4207b4ab0, 0x1, 0xc4206c0640)
	/workspace/anago-v1.11.0-beta.1.299+be2cfcf9e44b51/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:221 +0x4d
k8s.io/kubernetes/cmd/kubeadm/app/util/apiclient.PatchNode(0x19d0d00, 0xc42049c500, 0xc4204034e0, 0x9, 0xc4206c0640, 0x8b, 0x0)
	/workspace/anago-v1.11.0-beta.1.299+be2cfcf9e44b51/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/util/apiclient/idempotency.go:199 +0xb2
k8s.io/kubernetes/cmd/kubeadm/app/phases/patchnode.AnnotateCRISocket(0x19d0d00, 0xc42049c500, 0xc4204034e0, 0x9, 0xc42059a480, 0x23, 0x1, 0x0)
	/workspace/anago-v1.11.0-beta.1.299+be2cfcf9e44b51/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/patchnode/patchnode.go:33 +0x183
k8s.io/kubernetes/cmd/kubeadm/app/cmd.(*Init).Run(0xc42051a760, 0x198c260, 0xc42000c018, 0xc420624c00, 0xc420620100)
	/workspace/anago-v1.11.0-beta.1.299+be2cfcf9e44b51/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:426 +0x1678
k8s.io/kubernetes/cmd/kubeadm/app/cmd.NewCmdInit.func1(0xc4200dd180, 0xc4200ad6c0, 0x0, 0x2)
	/workspace/anago-v1.11.0-beta.1.299+be2cfcf9e44b51/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:155 +0x265
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc4200dd180, 0xc4200ad640, 0x2, 0x2, 0xc4200dd180, 0xc4200ad640)
	/workspace/anago-v1.11.0-beta.1.299+be2cfcf9e44b51/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:760 +0x2c1
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420160280, 0xc420590000, 0xc4200ddb80, 0xc4200dd180)
	/workspace/anago-v1.11.0-beta.1.299+be2cfcf9e44b51/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:846 +0x30a
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420160280, 0xc42000c010, 0x198c260)
	/workspace/anago-v1.11.0-beta.1.299+be2cfcf9e44b51/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:794 +0x2b
k8s.io/kubernetes/cmd/kubeadm/app.Run(0xc4203b21a0, 0xc4205cdf78)
	/workspace/anago-v1.11.0-beta.1.299+be2cfcf9e44b51/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:42 +0x149
main.main()
	/workspace/anago-v1.11.0-beta.1.299+be2cfcf9e44b51/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:27 +0x26
```

## What you expected to happen?

Dry run to complete with no panic

## How to reproduce it (as minimally and precisely as possible)?
Using containerd and the following `kubadm.conf`
```
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: 2a02:1348:17c:733f:24:19ff:fef1:ccfe
networking:
  serviceSubnet: fd00:1234::/110
kubernetesVersion: 1.11.0-beta.2
cloudProvider: external
criSocket: /var/run/containerd/containerd.sock
```

Running `sudo kubeadm init --dry-run --config=kubeadm.conf`

## Anything else we need to know?
Using containerd instead of docker

**Comment by neolit123** [comment]
it appears to panic because a node doesn't have `Annotations`.
this shouldn't happen, yet i'm not sure what's going on here.

try adding an annotation to see if the panic goes away:
https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/

but this still has to be fixed.

**Comment by luxas** [comment]
This isn't specific to containerd. I have a bugfix up here already: https://github.com/kubernetes/kubernetes/pull/65151

**Comment by timothysc** [comment]
fixed and merged.
